### ISSUE TITLE
Linux build error

### ISSUE THREAD

**Issue by Guoanshisb** [boogie-org/boogie#10]
Hi guys, 

I'm trying to build Boogie on a linux machine while I got this error message,
`mono ./nuget.exe restore Source/Boogie.sln`
`WARNING: The runtime version supported by this application is unavailable.`
`Using default runtime: v2.0.50727`
`Unhandled Exception: System.TypeLoadException: Could not load type 'NuGet.Program' from` `assembly 'NuGet, Version=2.8.60318.667, Culture=neutral, PublicKeyToken=null'.`
`[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type` `'NuGet.Program' from assembly 'NuGet, Version=2.8.60318.667, Culture=neutral,` `PublicKeyToken=null'.`

I'm using mono version 2.10.8.1

Thanks,
Shaobo

**Comment by delcypher** [comment]
Mono ``2.10.8.1`` is ancient. You should upgrade.

If you really don't want to upgrade you could try disable building the unit tests (you can easily disable building the unit tests projects) which are the only things that depend on ``NUnit`` (and hence ``nuget.exe``).

**Comment by Guoanshisb** [comment]
Got it. Thanks.
