### ISSUE TITLE
Printing error model with floating point (real) values

### ISSUE THREAD

**Issue by dhruvturakhia** [boogie-org/boogie#104]
I tried using the /printModel <n> functionality, but it ended up not being able to print the error model but throws a particular error

Prover error: Model parsing error: Invalid model: invalid element name 719.0, at line 2 (b -> 719.0)
Here is a test code to check:

[test.txt](https://github.com/boogie-org/boogie/files/2470942/test.txt)

**Comment by zvonimir** [comment]
Fixed by pull request #142.
