### ISSUE TITLE
Calling Boogie from emacs on Mac OS X (or any other unix system) 

### ISSUE THREAD

**Issue by germanD** [boogie-org/boogie#105]
I want to call Boogie from Emacs (using the [boogie-friends package](https://github.com/boogie-org/boogie-friends])) on Mac OSX. I ended up stealing my way [from Dafny](https://github.com/Microsoft/dafny/blob/master/Binaries/dafny), and created the following wrapper file

```(bash)
#!/usr/bin/env bash

# A wrapper calling Boogie.exe using mono

MONO=$(which mono)

# find the source directory for this script even if it's been symlinked [issue #185]
# from https://stackoverflow.com/questions/59895/
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
BOOGIE_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
BOOGIE="$BOOGIE_ROOT/Boogie.exe"

if [[ ! -x "$MONO" ]]; then
    echo "Error: Dafny requires Mono to run on non-Windows systems."
    exit 1
fi

if [[ ! -e "$BOOGIE" ]]; then
    echo "Error: Dafny.exe not found at $BOOGIE."
    exit 1
fi

"$MONO" "$BOOGIE" "$@"
```
and then set up  ``` flycheck-boogie-executable``` accordingly. However, I wonder if there was a more canonical approach available?

**Comment by bkragl** [comment]
I have the exact same script adapted from Dafny on my machine :)
I think it should be added to the repository. Any objections?

On Ubuntu, I noticed that you can directly call the Boogie.exe file (and point flycheck-boogie-executable to it) which invokes it using mono.
