### ISSUE TITLE
Syntax highlighting for Boogie in VSCode

### ISSUE THREAD

**Issue by stanlysamuel** [boogie-org/boogie#106]

**Comment by stanlysamuel** [comment]
Hi,

I am a PhD student at Indian Institute of Science. I am currently testing Boogie for my work. However, since I prefer to use VSCode as the editor, syntax highlighting for .bpl files is currently not supported. I wish to add this (trivial) support for Boogie (and if successful, many more) to VSCode. To do this, VSCode requires a TextMate Grammar file (.tmLanguage ) for the language to be supported (Boogie in my case). I checked the Boogie repository available online but I couldn't find a .tmLanguage or .tmLanguage.json file. I could only find support for vim (https://github.com/boogie-org/boogie/tree/master/Util/vim/syntax).

Thus, I wanted to ask if any of the contributors would have, by any chance, created such a grammar file. If not, I would like to try to make it, if time permits. In the latter case, I may have to look at the "This is Boogie 2" documentation if no other source is available. Also, please let me know if any external permissions (from Boogie contributors) are required for the same.

Stanly Samuel

**Comment by shazqadeer** [comment]
Looks like this issue is resolved.
