### ISSUE TITLE
Invoking Boogie with Spaces In Filenames

### ISSUE THREAD

**Issue by jon-whit** [boogie-org/boogie#11]
This is by no means a large issue, but it would be nice to enable spaces in filenames. If I have a Boogie program in a file called `test space.bpl` and I try to invoke Boogie on it, I get the error:

```
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.
*** Error: 'test': Filename extension '' is not supported. Input files must be BoogiePL programs (.bpl).
```

Is there a reason why this is not currently supported? I've been developing on [SMACK][1] and have had an inquiry about [this issue][2].

[1]: https://github.com/smackers/smack/
[2]: https://github.com/smackers/smack/issues/89

**Comment by delcypher** [comment]
This isn't a Boogie issue AFAICT. It's your shell. The default field separator is a space (if you use bash read about ``IFS``). You need to quote the file name.

I tried it under Linux on my system and if I quote the file name then verification appears to work correctly.

```
$ Binaries/Boogie.exe "use me.bpl" 
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.

Boogie program verifier finished with 1 verified, 0 errors
```

**Comment by jon-whit** [comment]
I am quoting the file name:

```
$ boogie "test space.bpl" 
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.
*** Error: 'test': Filename extension '' is not supported. Input files must be BoogiePL programs (.bpl).
```

**Comment by jon-whit** [comment]
I am using bash, and quoting the file name does not work. 

```
$ boogie "test space.bpl" 
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.
*** Error: 'test': Filename extension '' is not supported. Input files must be BoogiePL programs (.bpl).
```

**Comment by delcypher** [comment]
@jon-whit ``boogie`` is not a file that is part of this repository, nor is generated by Boogie's build process. 

Are you using the [``boogie`` wrapper script from the SMACK repo](https://github.com/smackers/smack/blob/master/bin/boogie) by any chance?

I just took a look at it and it has a bug in it (so does the Corral wrapper script) relating to handling arguments passed to it.

I've sent a [pull request to fix it](https://github.com/smackers/smack/pull/90) to fix it.

**Comment by delcypher** [comment]
Closing this because it's an issue with SMACK's wrapper and has nothing to do with Boogie's code.
