### ISSUE TITLE
Error with recursive generic procedure

### ISSUE THREAD

**Issue by cburke496** [boogie-org/boogie#112]
The following code:
```
type List T;
function tl<T>(List T): List T;

procedure Foo<T>(L: List T)
{
  call Foo(tl(L));
}
```
gives the error:
```
(5, 14): Error: more than one declaration of type variable: T
```
However, if I use a function instead of a procedure, it verifies just fine:
```
function FooF<T>(L: List T): bool
{
  FooF(tl(L))
} 
```

**Comment by cburke496** [comment]
I just realized that you don't even need the `tl` function. Just recursing on `L` is enough to break it.

**Comment by cburke496** [comment]
Turns out that separating the procedure into a pair of procedure and implementation that have different names for their type parameter is a workaround.

**Comment by RustanLeino** [comment]
This is a bug.
