### ISSUE TITLE
CSC : error CS0006

### ISSUE THREAD

**Issue by yueyuep** [boogie-org/boogie#115]
when i open boogie and build solution in vs2015 ,There was an error:
CSC : error CS0006: Metadata file 'K:\boogie-master\Source\Concurrency\bin\Debug\BoogieConcurrency.dll' could not be found.

CSC : error CS0006: Metadata file 'K:\boogie-master\Binaries\BoogieExecutionEngine.dll' could not be found

**Comment by nwuli** [comment]
@cpitclaudel 
when i open boogie and build solution in vs2015 according the guidence ,There was an error:
CSC : error CS0006: Metadata file 'K:\boogie-master\Source\Concurrency\bin\Debug\BoogieConcurrency.dll' could not be found.
CSC : error CS0006: Metadata file 'K:\boogie-master\Binaries\BoogieExecutionEngine.dll' could not be found. i try many methords and could't figue out.

**Comment by shazqadeer** [comment]
vs2015 is not supported.  Please try with newer version of VS and report back if the problem persists.
