### ISSUE TITLE
How to write invariant for a local var in a loop which increases by 2 per iteration

### ISSUE THREAD

**Issue by ZhangDingwen** [boogie-org/boogie#121]
For example,

```boogie
procedure howToWriteInvariantForThisSimpleCase()
{
  var i : int;
  i := 0;
  while(i < 4)
  invariant i <= 4;
  {
     i := i + 2;
  }
  // What I really want to ensure is i equals to 4 after the loop ends
  // assert i == 4;
}
```

and the verification result is 

```
input(6,3): Error BP5005: This loop invariant might not be maintained by the loop.
Execution trace:
    input(4,5): anon0
    input(5,3): anon2_LoopHead
    input(8,8): anon2_LoopBody

Boogie program verifier finished with 0 verified, 1 error
```

It made me confused, I don't know why Boogie can't proof the invariant i <= 4 hold. And when I replace i := i + 2 with i := i + 1, it works. So, how to write invariant for a local var in a loop which increases by 2 per iteration? (even increases by more than 2 per iteration)

**Comment by bkragl** [comment]
Your invariant `i <= 4` is not inductive. Imagine you start the loop in a state where `i == 3` which satisfies `i <= 4`. Then after the loop iteration you have `i == 5`, which does not satisfy the invariant anymore. This is what Boogie means by saying "This loop invariant might not be maintained by the loop".

One way to fix your example (and make the loop invariant inductive) is to add the extra invariant that `i` is a multiple of 2, i.e., `i mod 2 == 0`.
