### ISSUE TITLE
Prover error when using generic types

### ISSUE THREAD

**Issue by siddharth-krishna** [boogie-org/boogie#122]
The following example demonstrates the issue:
```
type Seq T;

function Seq_append<T>(s: Seq T, o: T) returns (t: Seq T);

type Invoc;

procedure {:atomic} {:layer 2} foo(this: Invoc) {}

procedure {:yields} {:layer 1} {:refines "foo"} bar(this: Invoc)
{
  yield;
}

// If you comment out the above two procedures, the error disappears
procedure test(x: Invoc, y: int)
  requires y > 0;
  ensures y > -1;
{}
```

Error:
```
$ boogie test.bpl
Boogie program verifier version 2.4.0.10404, Copyright (c) 2003-2014, Microsoft.
Prover error: line 29 column 19: invalid datatype declaration, unknown sort 'T@Invoc'
Prover error: line 140 column 19: invalid datatype declaration, unknown sort 'T@Invoc'

Boogie program verifier finished with 2 verified, 0 errors
```

As noted in the comment, if I don't use CIVL procedures or the "refines" annotation, the error does not happen.

(Observed with both Z3 version 4.5.0 and 4.8.4)

**Comment by shazqadeer** [comment]
CIVL does not support polymorphic Boogie.  Several examples in the
Test\civl folder can be verified only with /useArrayTheory which is
incompatible with polymorphic encodings implemented inside Boogie.  But
/useArrayTheory is not needed for all examples.  It would be nice to
support polymorphism for those examples where CIVL does not need
/useArrayTheory.  If there is a volunteer to implement the support for
CIVL, I am happy to work together.

**Comment by siddharth-krishna** [comment]
I see, thank you. I'm a bit swamped at the moment, but I'll keep this in mind if I have time sometime in the future!
