### ISSUE TITLE
Can boogie be builded for arm platform?

### ISSUE THREAD

**Issue by stdvivi** [boogie-org/boogie#127]
Can boogie be builded for arm platform?

**Comment by bkragl** [comment]
It seems that Mono supports ARM (https://www.mono-project.com/docs/about-mono/supported-platforms/).

Also, .NET Core introduced ARM32 support in version 2.1 (https://devblogs.microsoft.com/dotnet/announcing-net-core-2-1/), and will introduce ARM64 support in version 3.0 (https://github.com/dotnet/announcements/issues/82).

Did you try and ran into problems?

Anyway, you would also need to make sure that Z3 can be compiled for ARM.

**Comment by stdvivi** [comment]
@bkragl We have no  ARM enviroments as of now. Just need to do the investigation and plan for the transter.Thank you very muvh!
