### ISSUE TITLE
compute the weakest precondition of a procedure

### ISSUE THREAD

**Issue by bitcalc** [boogie-org/boogie#148]
Hi,

I'm new to Boogie and want to find the code that computes the weakest precondition of a procedure and use it in my verification work. According to the [Boogie paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2005/01/krml160.pdf), Boogie computes the weakest precondition already. What I want is getting the weakest precondition (WP) of a procedure for given asserts inside the procedure. I also want to easily query a computed WP by a given procedure. Based on this, I hope to conduct procedural level modular verification using Boogie's existing functionalities.

Can anyone help explain how to do it in Boogie and point me to where the related code is?

**Comment by zvonimir** [comment]
Could you please clarify more precisely what you mean by "procedural level modular verification"?
I would say that this is what Boogie is already doing (modular verification using pre- and post-conditions and loop invariants), but clearly you are looking for something else.
Formal verification terminology is often overloaded, and so clarifying this would be helpful to make sure we are on the same page.

**Comment by bitcalc** [comment]
I mean what you said in this context: using pre- and post-conditions and loop invariants to verify one procedure at a time; but in a controlled manner. The controlled manner means that I can programmatically decide the procedure whose pre- and post-conditions to be returned. For example, given a call graph as the following (`->` indicates the call relation):
```
A -> B -> C -> D
A -> E -> F
     E -> G -> H -> F
```
I want to compute F's WP, and then compute H's. When I compute H's WP, F's post-conditions might change, which in turns requires re-computation of F's pre-condition in order to satisfy the changed post-condition. After re-computing F's pre-condition, I need to re-compute H's again. This process is essentially a fixed point computation which can be put into the abstract interpretation framework.

Boogie already has the ability of computing WP of a procedure, but I'm not sure if it can do what I described above. If not, what is the best way to achieve it by leveraging existing code in Boogie?

**Comment by bitcalc** [comment]
I looked through some boogie code but was unable to figure out which part is most relevant. I guessed that the ConditionGeneration and its nine subclasses should have the WP computation somewhere, but I haven't spotted related functions. Can anyone point me to the right place or suggest an efficient way to do what I want?

**Comment by zvonimir** [comment]
I am not familiar with this part of Boogie code, and so I cannot provide you with details related to your last question.

Coming back to your post above from a week ago. What you are describing seems a bit like computing procedure summaries and then refining them (i.e., making them more precise) as needed, until convergence. Corral implements something like that - its initial "summaries" are the most abstract ones (just uninterpreted functions), which are right away refined into the most precise ones (by procedure inlining). I think that at some point there was a paper published that does a more "gentle" refinement by computing procedure summaries incrementally. I can't remember the exact title, but I think that Nishant Sinha was one of the coauthors. @akashlal maybe you remember this paper?

**Comment by RustanLeino** [comment]
@bitcalc Yeah, as @zvonimir said, Corral computes some procedure summaries for you. Depending on the size of your problem, maybe you can use Boogie's inlining features to sidestep the need for procedure specifications altogether (but this moves you away from modular verification).

When in your example you say "`F`'s post-conditions might change", I suppose you have in mind something that is going to change the definition of `F` in the program (perhaps changing it from a summary that's been computed). If you feed an updated program to Boogie, you can take advantage of Boogie's caching features, which will reverify only those parts of your programs that effectively have changed.

*) For the inline features, see examples in the Boogie test suite.
**) For information about Boogie's caching, see "The Dafny Integrated Development Environment" and "Fine-Grained Caching of Verification Results" by Leino and Wüstholz.

**Comment by bitcalc** [comment]
I'm not looking for inlining or caching. I'm seeking to get the weakest precondition (WP) of a procedure when given a postcondition. In my example above, when I compute F's WP first, F's postcondition is empty (or true), but H might have code looking like the following:

```
procedure H() {
    ....
    call F();
    assert(logic-expr);
    ....
}
```
Then, F's postcondition at this call site is not empty, which must derive or include `logic-expr`. This is what I meant by saying "F's postcondition might change."

Let me explain what I want again from another perspective (the top-down). For the same call graph:
```
A -> B -> C -> D
A -> E -> F
     E -> G -> H -> F
```
If I compute the WP of A first, then at the last call site of E I get E's required postcondition. I pause the WP computation of A and start computing the WP of E. At the last call site of G in E, I pause the WP computation of E and start computing the WP of G. The process continues until I compute F's WP after suspending H's WP computation. After finishing computing F's WP, I resume H's WP computation, and then of G, and then of E. In E, when I reach F again along `A -> E -> F`, F's postcondition may be different from the first time when I computed F's WP inside H. Here, I need to choose whether I should use context-sensitive or insensitive summary, which is the post- and pre-condition, of F. Whichever I select, I need to re-compute F's WP. 

The important elements here are the WP computation of a procedure when given a postcondition and the fixed-point computation. I really want to leverage existing WP computation functionality (in Boogie, or Corral, or whichever tool already has it).

This process is not Corral's refinement either. Of course, if Corral can give me the WP of some procedures, I'm glad to use its results. For example, when I compute A's WP along `A -> B -> C -> D`  if Corral somehow can let me know that the WP of B which includes `B -> C -> D` is `wpb` for a given postcondition `pc`, then I can use the result directly in the fixed-point computation.

**Comment by bitcalc** [comment]
I found code in boogie/Source/VCGeneration/VC.cs and wlp.cs that looks like compute the WP, especially those `xxxVC` functions called in `GenerateVCAux`. I'm not sure if I can call any of the functions directly to get the WP of a procedure with a given postcondition. If not, what's the best way to re-use the current code to write such a function, such that it facilitates the development of the fixed-point computation described above?

**Comment by shazqadeer** [comment]
@bitcalc: Questions for you:
- Do you expect the input to your tool to contain loops and/or recursive procedures?
- Is the input to your tool going to be an annotated or unannotated Boogie program, i.e., do you expect the input to contain pre/post-conditions and loop invariants?
- If the tool allows loops and recursion and also unannotated programs, how will it deal with these features?

Boogie's VC generation is designed to work for annotated Boogie programs.  Procedure inlining, when used in a controlled manner, can avoid the need for pre/post-conditions of non-recursive procedures but at a significant computational cost.  If your tool aims to analyze unannotated Boogie program, then reuse of existing VC generation machinery may not be the best option.  It all depends on the goals of the analysis: generality of inputs, worst-case computational complexity, etc.

**Comment by bitcalc** [comment]
@shazqadeer Thanks for the comments. Here are the answers to your questions:
1. The original program contains loops, but after looping havoc, which Boogie already does, and annotating with invariants, it's safe to say that at the WP computation stage there are no loops.
2. Our current input doesn't have recursive procedures. But for predictable few cases when they occur, in most cases we can rewrite code or assert goals such that the recursion doesn't involve conditions that needed to prove those goals.
3. My tool would be processing Boogie code generated from Smack, so the input is annotated Boogie program with pre- and post-conditions and loop invariants.

**Comment by bitcalc** [comment]
> I'm not looking for inlining or caching...

Caching is, of course, useful in my case when the post-condition of a procedure whose WP has been computed can derive the post-condition needed at a new call site. In this case, there is no need to re-compute the procedure's WP if its WP can be derived before the call site. However, if the WP is too strong and cannot be derived before the call site, a re-computation is still required.

**Comment by shazqadeer** [comment]
Ok, let us say the input to your tool is recursion-free and loop-free program whose procedures are annotated with pre and post-conditions.  Since the procedures are already annotated, why do the fixpoint and WP-calculation at all?  Why not just use the normal Boogie verifier to verifier all the annotated procedures where the postcondition of a procedure is used to verify callers modularly?

**Comment by bitcalc** [comment]
@shazqadeer It looks like that my last sentence `the input is annotated Boogie program with pre- and post-conditions and loop invariants` caused your confusion. Let me clarify it. The initial input Boogie program only has loop invariants and asserts. Procedures have empty pre- and post-conditions. The non-empty precondition is computed according to the assert goals and postconditions by the WP and fixpoint process.

**Comment by shazqadeer** [comment]
@bitcalc :  Thanks for the clarification.  I finally understand the problem statement for your tool.  It is the following:

Input: An unannotated, loop-free, and recursion-free program
Output: Either a counterexample leading to an assertion failure or pre/post-conditions that are sufficient to prove all assertions in the program modularly

It is instructive to compare the problem above to the following problem that Corral attempts to solve:

Input: An unannotated, loop-free, and recursion-free program
Output: Either a counterexample leading to an assertion failure or a "proof" guaranteeing the absence of assertion failures

The notion of proof for Corral is not pre/post-conditions that can be checked modularly.  Rather, it is a partial unfolding of the call tree of the program that is sufficient to prove absence of errors.

I am providing all this information simply as background so you can make sense of the relevant literature.

The VC generation in Boogie is not going to be convenient for doing what you want because Boogie is highly optimized for generating verification conditions for fully-annotated procedures.  I believe what you want is a way to represent pre/post-conditions of a procedure in terms of pre/post-conditions of other procedures.   Once you have a logical representation of all these relationships, you want to do some fixpoint calculation.

I have two suggestions:
- take a look at Corral papers to see how it uses Boogie infrastructure to achieve its ends.  At the least, try to understand how Corral extracts the information it needs from Boogie VC generation.
- take a look at the SeaHorn framework; perhaps it provides a natural way to express what you want.

**Comment by bitcalc** [comment]
@shazqadeer Thanks for your suggestions. I'll look into your pointers.

> ... I believe what you want is a way to represent pre/post-conditions of a procedure in terms of pre/post-conditions of other procedures. Once you have a logical representation of all these relationships, you want to do some fixpoint calculation.

I would say that all these relationships are intended to be established by the WP computation and the fixed point calculation. If I already have stable pre- and post-conditions of procedures, then it means the fixed point calculation completes.

If Boogie is not convenient to use for the WP computation of procedures, what is the best choice to do it on Boogie code?

**Comment by shazqadeer** [comment]
> I would say that all these relationships are intended to be established by the WP computation and the fixed point calculation. If I already have stable pre- and post-conditions of procedures, then it means the fixed point calculation completes.

Right.  I meant that preconditions and postconditions of procedures are unknowns that are connected to each other via constraints and the process of abstract interpretation is trying to come up with appropriate expressions for those unknowns such that the constraints are satisfied.

> If Boogie is not convenient to use for the WP computation of procedures, what is the best choice to do it on Boogie code?

I don't know.  I believe you can reuse most of Boogie infrastructure but it is unlikely you will be able to reuse the VC generation as a black box.

In addition to understanding how Corral  uses Boogie infrastructure, another thing you can take a look at is the implementation of the Houdini algorithm inside the Boogie codebase itself. Houdini solves the following problem:

Input: A program with a collection of candidate preconditions and postconditions 
Output: Either a subset of the candidate annotations that modularly proves absence of assertion failures or a guarantee that such a modular proof cannot be found using the candidates
