### ISSUE TITLE
crlf issues in git

### ISSUE THREAD

**Issue by kenmcmil** [boogie-org/boogie#15]
Git is a bit unix-centric and tends to get confused by carriage returns in files. The result is you get whole-file diffs when editing on different platforms because one version has crlf line endings and one version has lf line endings. This makes branching and merging impossible.  I would suggest adding this line to the file .gitattributes in the main directory:

* text=auto

If you do this git will check out files with the appropriate line endings for your platform but check them in  in some standard way (I think in unix style). I also think this will update the whole repository once to make the line endings standard.

Or if you want crlf always, even on unix/mac, then use this:

* text eol=crlf

I think either is OK but the default behavior creates a mess when you edit on both unix and windows.

**Comment by cpitclaudel** [comment]
I'm not sure that's a good idea, unless we make one giant commit that normalizes everything to LF first. At the moment stuff in the repo is mostly using CRLF, so with text=auto (which is more or less the default on Windows anyway) we'll get walls of pink everytime someone makes a change on Windows (see the latest few commits).

**Comment by cpitclaudel** [comment]
The giant commit approach is probably the best, though, so we might want to go ahead and do that.

**Comment by kenmcmil** [comment]
My understanding is it will do the giant commit when you change the eol option. It doesn't seem to me to matter that much whether it is all lf or all crlf, so long as it is consistent. Choosing eol=crlf seems a reasonable option given that most boogie developers are on windows.

**Comment by cpitclaudel** [comment]
Indeed, as long as we push that option so that it is on by default on Windows boxes, eol = crlf seems like a nice option. We'd have to normalize back some files, too.

**Comment by delcypher** [comment]
I don't like huge formatting commits but here it is really necessary. I'd prefer not to force ``clrf`` on everyone. I'd prefer if our ``.gitattributes`` file was like this

```
# Autodetect text files and ensure that we normalise their
# line endings
* text=auto

# These should always be checked out with crlf line endings
*.sln text eol=crlf
*.csproj text eol=crlf
*.cs text diff=csharp eol=crlf
*.fs eol=crlf
*.fsproj eol=crlf
*.fsy eol=crlf
*.resx eol=crlf
*.vsixmanifest eol=crlf
App.config eol=crlf

# These should always be checked out with lf line endings
*.sh eol=lf
Makefile eol=lf
.gitignore eol=lf
.gitattributes eol=lf

# For the remaining files the line endings of checked out
# files is defined by the ``core.eol`` git config variable.
# By default this is the native line ending for the platform.
```

This way we only make the files that we know need to have ``crlf`` line endings be that way on checkout (similarly for ``lf``). For the others the user can choose how they are checked out.

However if this is too complicated, I think this would also be acceptable

```
# Autodetect text files and ensure that we normalise their
# line endings and on checkout use crlf
* text=auto eol=crlf


# These should always be checked out with lf line endings
*.sh eol=lf
Makefile eol=lf
.gitignore eol=lf
.gitattributes eol=lf
```

My version of git seems to tell me that all the files will be normalised when I add the ``.gitattributes`` file however the git documentation (``man gitattributes``) does show this warning

```
               Note
               When text=auto normalization is enabled in an existing repository, any text files containing CRLFs should be normalized. If they are not they will be normalized the next time someone tries to
               change them, causing unfortunate misattribution. From a clean working directory:

               $ echo "* text=auto" >>.gitattributes
               $ rm .git/index     # Remove the index to force Git to
               $ git reset         # re-scan the working directory
               $ git status        # Show files that will be normalized
               $ git add -u
               $ git add .gitattributes
               $ git commit -m "Introduce end-of-line normalization"

           If any files that should not be normalized show up in git status, unset their text attribute before running git add -u.
```

so whoever does this should probably do the above.

**Comment by cpitclaudel** [comment]
Is there a reason to use CRLF for .cs files?

**Comment by delcypher** [comment]
@cpitclaudel My assumption was that files that Visual Studio consumes (etc. C# source files) should probably have ```crlf`` line endings. I've not tried Visual Studio with ``lf`` line endings so I'm not sure if it actually matters.

**Comment by cpitclaudel** [comment]
http://stackoverflow.com/questions/3802406/configure-visual-studio-with-unix-end-of-lines seems to suggest it's not an issue (i.e. VS won't complain about LF line endings, though it will still give new files CRLF endings by default, unless configured otherwise).

**Comment by kenmcmil** [comment]
It seems best to me to have the line endings match the default for the platform (i.e., using auto). For example, if you use lf on all platforms, then new files created with VS will still have crlf. My impression is that the crlf line endings will be checked in. Then they will be converted to lf on checkout, so at the next commit there will be a whole-file change.

**Comment by delcypher** [comment]
@kenmcmil 
> It seems best to me to have the line endings match the default for the platform (i.e., using auto).

That's actually not what ``* text=auto`` does.  What this will do is have git try to guess which files are binary and which files are text. For files it guesses are binary it will not try to do line normalisation, for files it thinks are text it will perform line normalisation.

If we don't set the ``eol`` attribute on files and the user doesn't modify the default value of their ``core.eol`` (or they explicitly set it to ``native``) then the normalised files will be checked out with the platform native line ending. However to me it makes sense to force ``crlf`` in certain cases (.e.g ``.csroj`` and ``.sln`` files). Conversely it makes sense to force ``lf`` in certain cases (e.g. ``Makefile``).

>  My impression is that the crlf line endings will be checked in.

Not quite. If the file has line normalisation enabled (i.e. ``text`` attribute) then the file is **always stored as if it had** ``lf`` **line endings** regardless of what is used in the checked out files. The ``eol`` attribute controls what the line endings will be when normalised files are checked out but internally git will always store them with ``lf`` line endings.

**Comment by kenmcmil** [comment]
OK, that is consistent with observation. That is, with text=auto, git normalizes the line endings on commit. Now exactly how it decides that files are text I don't know. Also I don't know how to get line ending normalization for specific file types. However, it seems reasonable to use "* text=auto" and then make exceptions for any specific files or file types you don't want treated in this way (that is what Z3 does).

**Comment by delcypher** [comment]
962f8d5252b3f5ec4d19e0cd2a430934bd55cc6d implements this.
