### ISSUE TITLE
Boogie fails with a parse error if a procedure name is `yield`

### ISSUE THREAD

**Issue by alexanderjsummers** [boogie-org/boogie#150]
It would be useful to report that yield is a reserved name; especially to a vanilla/novice Boogie user, the parse error is probably surprising.

**Comment by shazqadeer** [comment]
I just tried Boogie and discovered that this is a uniform issue with all keywords, not just yield.  Better error messages across all of that is low priority for now.  So closing this issue.  But, thanks a ton for reporting.
