### ISSUE TITLE
Can someone explain the meaning of VCVarieties?

### ISSUE THREAD

**Issue by bitcalc** [boogie-org/boogie#159]
I'm looking into Boogie's WP and VC computation and failed to find documentation of the variety of VCs. Can someone help me understand what their differences are and what they're made for? I'm interested in using Boogie's WP computation functionality in a verifier and want to make an informed decision of which one I should use.
```
public enum VCVariety {
      Structured,
      Block,
      Local,
      BlockNested,
      BlockReach,
      BlockNestedReach,
      Dag,
      DagIterative,
      Doomed,
      ...
    }
```

**Comment by shazqadeer** [comment]
VCVariety has been eliminated from Boogie. Boogie now supports only one way to generate VCs.

**Comment by bitcalc** [comment]
Which one is supported now? The DagIterative?

**Comment by shazqadeer** [comment]
Yes. What is supported now used to be referred to as DagIterative earlier.

If you look deeper into the VCgen code, you will see two methods---LetVC and DagVC--- which are invoked as follows.

if (cce.NonNull(CommandLineOptions.Clo.TheProverFactory).SupportsDags || CommandLineOptions.Clo.FixedPointEngine != null) {
        vc = DagVC(cce.NonNull(impl.Blocks[0]), controlFlowVariableExpr, label2absy, new Hashtable/*<Block, VCExpr!>*/(), proverContext, out assertionCount);
      } else {
        vc = LetVC(impl.Blocks, controlFlowVariableExpr, label2absy, proverContext, out assertionCount);
      }

The above code means that LetVC will be invoked unless some special things happen.  I implemented LetVC and understand it.  I don't understand the purpose or need for DagVC.
