### ISSUE TITLE
Boogie testing relies on lit.exe, which seems difficult to obtain for Windows

### ISSUE THREAD

**Issue by alexanderjsummers** [boogie-org/boogie#163]
It would be great to either run tests in a way which doesn't depend on this tool, or provide instructions for how it can be obtained. The llvm distributions (for Windows) don't seem to include it.

**Comment by bkragl** [comment]
See here:
https://github.com/boogie-org/boogie/blob/master/Test/README.md

I remember installing and running lit on Windows without problems.

**Comment by bkragl** [comment]
Just checked on a Windows machine. With a Python installation run
```
pip install lit OutputCheck
```
and you are good to go.
