### ISSUE TITLE
Source tree contains prebuilt binary

### ISSUE THREAD

**Issue by FabianWolff** [boogie-org/boogie#167]
In `Util/VS2010/Boogie/BoogieLanguageService/Resources/`, there is a binary file called `Irony.dll` with no indication of where it's from, who compiled it, where the original source code can be found etc. (though I suppose it's from [this project](https://github.com/IronyProject/Irony)?).

This is a problem for Linux distributions such as Debian, whose policy demands that source code under a free license be made available for all binaries. One option for Debian would be to manually repack the Boogie source tarball and explicitly remove this file; another, less practical one might involve copying the source code for `Irony.dll` into the Debian package.

But the most simple and clean solution, in my view, would be to drop `Irony.dll` from the Boogie source tree; binaries and generated files usually don't belong into a source code repository, anyways, I'd say.

What do you think, would it be possible to drop `Irony.dll`? Or would this move be impractical/cause too large an overhead for Visual Studio users?

**Comment by shazqadeer** [comment]
I would be shocked if the contents of Util/VS2010 are still relevant. That is a very old version of Visual Studio.

@RustanLeino : I was poking into the Util folder.  It is likely there is a bunch of stale stuff there that could be deleted.  Could you please take a look and do the needful?  I am not confident about making changes there.

**Comment by RustanLeino** [comment]
Yes, let's delete those old things. Here are the PRs, ready to be merged.

https://github.com/boogie-org/boogie/pull/170
https://github.com/boogie-org/boogie/pull/171

**Comment by shazqadeer** [comment]
Thanks.  Those PRs have been merged.  Closing this issue.
