### ISSUE TITLE
Incompatible with Z3 which has changed the parameter name from "model_compress" to "model.compact"

### ISSUE THREAD

**Issue by junkil-park** [boogie-org/boogie#169]
In "boogie/Source/Provers/SMTLib/Z3.cs", Boogie sets the Z3 parameter "model_compress" to be false. This cause a problem with the latest Z3 (4.8.7+) which has changed the parameter name from "model_compress" to "model.compact".

**Comment by shazqadeer** [comment]
@bkragl :  I recall discussing a similar issue with you.  Thoughts?

**Comment by bkragl** [comment]
Yes, Nikolaj pointed out this change when I reported a segfault in Z3:
https://github.com/Z3Prover/z3/issues/2707

I think that the code that sets the Z3 parameters should be revised in general.

**Comment by zvonimir** [comment]
Yes! Cleaning up the code that sets up solver parameters has been on my mind for a long time now.
Should we create a separate issue for that and discuss it there?

**Comment by shazqadeer** [comment]
@zvonimir : Please create a separate issue.  I am closing this one.
