### ISSUE TITLE
Boogie compilation errors under mono (without mono-develop)

### ISSUE THREAD

**Issue by utting** [boogie-org/boogie#17]
Boogie does not compile (on OS X 10.10.3) using just mono (Mono JIT compiler version 4.0.1).
It gives the following compilation errors:
------------------------------------------------------------------------------
Errors:

/Users/utting/tools/boogie/boogie/Source/Boogie.sln (default targets) ->
(Build target) ->
/Users/utting/tools/boogie/boogie/Source/UnitTests/TestUtil/TestUtil.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.0.1/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	ProgramLoader.cs(11,11): error CS0117: `NUnit.Framework.Assert' does not contain a definition for `IsNotNullOrEmpty'
	ProgramLoader.cs(12,11): error CS0117: `NUnit.Framework.Assert' does not contain a definition for `IsNotNullOrEmpty'

	 2 Warning(s)
	 2 Error(s)
------------------------------------------------------------------------------

This seems to be because Source/UnitTests/TestUtil/ProgramLoader.cs calls the IsNotNullOrEmpty method, which is not supported under the **NUnitLite** framework, which is what comes standard with mono.
(mono-develop includes the full NUnit framework, so Boogie does compile within the IDE, but it should be possible to compile with just the command line mono, as the docs suggest.)

A possible fix is to change lines 11-12 of ProgramLoader.cs from:
			Assert.IsNotNullOrEmpty (programText);
			Assert.IsNotNullOrEmpty (fileName);
to:
			Assert.IsNotNull(programText);
			Assert.IsNotEmpty (programText);
			Assert.IsNotNull(fileName);
			Assert.IsNotEmpty(fileName);

Once this is done, boogie compiles correctly using the command line version of mono:
  xbuild Source/Boogie.sln
         ...
	 51 Warning(s)
	 0 Error(s)

Thanks
Mark Utting

**Comment by delcypher** [comment]
> but it should be possible to compile with just the command line mono, as the docs suggest.)

It is possible, read the [README.md](https://github.com/boogie-org/boogie#linuxosx) before complaining something doesn't work. You need to use NuGet to grab the NUnit package.
