### ISSUE TITLE
man pages for boogie

### ISSUE THREAD

**Issue by FabianWolff** [boogie-org/boogie#176]
As far as I can see, there are currently no "official" man pages available for Boogie.

Somebody once wrote man pages for the Debian package:
- https://salsa.debian.org/debian/boogie/blob/master/debian/boogie.1
- https://salsa.debian.org/debian/boogie/blob/master/debian/bvd.1

It seems ill-advised to me to try to maintain Debian-specific man pages, given that a) whoever works on the Debian package probably doesn't have the information about new/altered options/behavior available first-hand, and b) other users who aren't using the Debian package might like to have man pages as well.

Would you like to take over the man pages from the Debian package? The author has [released](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944876#20) them under the same license as the rest of Boogie, so copyright shouldn't be an issue (unless, of course, you require all copyright to be signed over to Microsoft; I don't know about your internal processes in this regard, but if that's the case, I would recommend contacting the author; he's still active and reachable).

**Comment by shazqadeer** [comment]
The Boogie developers currently do not have the bandwidth to take over the man pages.  Thanks for the offer.
