### ISSUE TITLE
Emacs mode

### ISSUE THREAD

**Issue by cpitclaudel** [boogie-org/boogie#18]
Hi all,

I've rewritten the [Boogie mode](https://github.com/boogie-org/boogie-friends) from scratch, and it's on MELPA now. It comes with some support for completion, better syntax highlighting, support for tracing and launching the axiom profiler, real-time verification, and a few other goodies. 

Are there objections to my pointing to that instead in the Util directory and removing the existing `boogie-mode.el`?

Clément.

**Comment by shazqadeer** [comment]
Emacs support for Boogie is available in https://github.com/boogie-org/boogie-friends
