### ISSUE TITLE
Strange integer multiplication behavior seen in code generated by Dafny

### ISSUE THREAD

**Issue by echuber2** [boogie-org/boogie#188]
Edit: As mentioned in the linked Dafny issue, this issue was first found by @nishantjr.

Sorry if this is a crosspost of sorts and that's against some kind of rule, but I was messing around with Dafny and it seemed like the Boogie code generated was not multiplying integers correctly in counterexamples. I can't tell if this is due to a bug in Dafny, or in Boogie, or if I just have no idea what I'm doing.

Examples are shown at the Dafny issue for reference, here: https://github.com/dafny-lang/dafny/issues/488

I tracked (some of) the behavior down to this line:
https://github.com/boogie-org/boogie/blob/044e533713346840b55e53c33082911fd077d299/Source/AbsInt/IntervalDomain.cs#L898
What exactly is Boogie trying to do with the bounding interval for integer multiplication here? Is it simply that Dafny is applying this transformation at incorrect times?

**Comment by zvonimir** [comment]
Could you generate and post a (small) Boogie program that shows this bug?
It is hard to debug this without having a test for it.

Otherwise, the Boogie code you are referring to is related to abstract interpretation for generating invariants, which should not be needed for you example. So I am wondering if this is due to incompleteness of Z3 non-linear arithmetic.

**Comment by echuber2** [comment]
Thanks for following up. The info above and in the linked Dafny issue are all I've got to contribute -- @nishantjr found the example that gives the erroneous counterexample and I was puzzling over it out of curiosity. I'll let him add to this if he wants to.

**Comment by nishantjr** [comment]
@zvonimir This is a Boogie translation of the Dafny program that displays this error.

```
procedure foo(n:int)
{
    assert ( ((n*(n+1)) div 2) + ((n*(n+1)) div 2) == (n*(n+1)) );
}
```

I've not been able to find documentation for the integer `div` operation. So I'm not sure if this this particular example needs additional axioms to go through. Looking at the Dafny translation to boogie, the only axioms for integer division is:

```
axiom (forall x: int, y: int :: { Div(x, y): int } Div(x, y): int == x div y);
```

**Comment by shazqadeer** [comment]
From the description of the problem, it appears to be prover flakiness in the presence of non-linear arithmetic.  Therefore, closing this issue.
