### ISSUE TITLE
.NET Framework and .NET Core project files conflict with each other

### ISSUE THREAD

**Issue by robin-aws** [boogie-org/boogie#190]
See https://github.com/microsoft/msbuild/issues/1924.

The symptom is that if you build a ***-NetCore.csproj project in a directory and then the older ***.csproj file in the same directory you get an extremely unhelpful error message:

```
a483e79acc1e:Model salkeldr$ dotnet build Model-NetCore.csproj 
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 2.71 sec for /Users/salkeldr/Documents/GitHub/boogie/Source/CodeContractsExtender/CodeContractsExtender-NetCore.csproj.
  Restore completed in 2.71 sec for /Users/salkeldr/Documents/GitHub/boogie/Source/Model/Model-NetCore.csproj.
  CodeContractsExtender-NetCore -> /Users/salkeldr/Documents/GitHub/boogie/Source/CodeContractsExtender/bin/Debug/netcoreapp3.1/BoogieCodeContractsExtender.dll
  Model-NetCore -> /Users/salkeldr/Documents/GitHub/boogie/Source/Model/bin/Debug/netcoreapp3.1/BoogieModel.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.75
a483e79acc1e:Model salkeldr$ msbuild  Model.csproj 
Microsoft (R) Build Engine version 16.3.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2020-02-05 10:53:00 AM.
Project "/Users/salkeldr/Documents/GitHub/boogie/Source/Model/Model.csproj" on node 1 (default targets).
/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/xbuild/Microsoft/NuGet/Microsoft.NuGet.targets(186,5): error : Your project does not reference ".NETFramework,Version=v4.5" framework. Add a reference to ".NETFramework,Version=v4.5" in the "TargetFrameworks" property of your project file and then re-run NuGet restore. [/Users/salkeldr/Documents/GitHub/boogie/Source/Model/Model.csproj]
Done Building Project "/Users/salkeldr/Documents/GitHub/boogie/Source/Model/Model.csproj" (default targets) -- FAILED.

Build FAILED.

"/Users/salkeldr/Documents/GitHub/boogie/Source/Model/Model.csproj" (default target) (1) ->
(ResolveNuGetPackageAssets target) -> 
  /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/xbuild/Microsoft/NuGet/Microsoft.NuGet.targets(186,5): error : Your project does not reference ".NETFramework,Version=v4.5" framework. Add a reference to ".NETFramework,Version=v4.5" in the "TargetFrameworks" property of your project file and then re-run NuGet restore. [/Users/salkeldr/Documents/GitHub/boogie/Source/Model/Model.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.51

```

The suggested fix seems to be to add a Directory.Build.props in the root of the repo that relocates the `obj` directory for the new project files (modified to fit the convention in Boogie):

```
<Project>
  <PropertyGroup Condition="$(MSBuildProjectName.Contains('-NetCore'))">
    <BaseIntermediateOutputPath>obj_core\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
```

**Comment by shazqadeer** [comment]
@bkragl , @michael-emmi : Are we going to fix this issue?  If not, suggest a workaround and close it.  For me, "git clean -dfx" between an msbuild build and a .NET core build always does the right thing.  But I can imagine this is not convenient.

**Comment by bkragl** [comment]
I also do `git clean -dfx` to avoid any conflicts.

I'm not sure if the suggested file should be added to the repository. But if we do, I'd suggest flipping the condition to put the object files of the old build somewhere special.

**Comment by shazqadeer** [comment]
Is there any reason to continue to support building with .NET Framework as well as .NET Core?  Perhaps we can just move to .NET Core and stop supporting the old build mechanism.

**Comment by zvonimir** [comment]
I agree with removing support for .NET Framework. Maintaining both is probably not a good idea in the long run.

**Comment by akashlal** [comment]
I still need Boogie/Corral to run on machines that just have .NET Framework. There is probably an easier way of having the two builds without needed two different sets of `csproj` files. On example is [coyote](https://github.com/microsoft/coyote) that builds for multiple .NET platforms. But I'm no expert on this.

**Comment by shazqadeer** [comment]
It looks like @bkragl  and @michael-emmi (the creators of the current build discipline) do not want to take any action on this issue.  It also looks like we need to continue to support both builds for the time being.  Hence, I am closing this issue.

@akashlal:  Do you think you could gradually those pesky machines off of their dependency on .NET Framework.  I am afraid we are moving slowly but surely towards a .NET Core only world in Boogie.

**Comment by robin-aws** [comment]
@shazqadeer Note this issue was not a request to remove .NET Framework support, but a bug in the current dual support.

Please re-open this unless there is also no interest in fixing the bug. I suggest that it's worth it, given how frustrating it is to figure out the root cause when bitten by it.

**Comment by shazqadeer** [comment]
@bkragl , @michael-emmi : Do you want to fix the problem?  An explicit yes/no would be helpful.

**Comment by bkragl** [comment]
I'll try to include this in another PR in the upcoming days.

**Comment by bkragl** [comment]
The above solution does not fully solve the problem. Applying it results in the following error in the .NET Core build.

```
obj/Debug/netcoreapp3.1/.NETCoreApp,Version=v3.1.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [/home/bkragl/Code/boogie/Source/CodeContractsExtender/CodeContractsExtender-NetCore.csproj]
```

It can be fixed by adding `<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>` to the confiuration, but I don't really want to do that because (a) I don't fully understand the consequences of omitting this information form the assemblies, and, more importantly, (b) the error above indicates that there might be other strange interferences between the two builds.

So IMO we should add some troubleshooting information to `README.md` that warns from running both builds in the same directory.

**Comment by shazqadeer** [comment]
@bkragl : Please add the appropriate troubleshooting information to README.md and close this issue.
