### ISSUE TITLE
Boogie fixed point engine

### ISSUE THREAD

**Issue by shazqadeer** [boogie-org/boogie#198]
@kenmcmil , @akashlal , @shuvendu-lahiri : I am looking into the VC generation code in Boogie and trying to figure out what cleanup is required.  I came across the  file FixedpointVC.cs with a lot of interesting code in it.  Is this code being maintained and used in Microsoft? Are there any tests for it?

cc: @RustanLeino, @michael-emmi, @zvonimir, @bkragl

**Comment by kenmcmil** [comment]
That sounds like it is part of the interface to Horn solvers that I hacked in long ago. However, I'm not using or maintaining it, so it has probably suffered from bit rot. It is probably only used from corral. If there are no current users, it might be best to deprecate it.

**Comment by akashlal** [comment]
I remember now. Its not central to Corral, but there are some folks who experiment with this code, so best to keep it for now.
