### ISSUE TITLE
Large modifies clauses cause a huge blowup

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#20]
We have SMACK-generated Boogie files with very large modifies clauses on all procedures. We are inlining procedures using Boogie, and so my hunch was that most modifies clauses should just be noops in that case. However, we are seeing a huge blowup inside Boogie, which likely happens during VC generation phase since Z3 does not even get a chance to be invoked.

Does anyone have any experience with this issue?

Is there maybe a Boogie switch that we can use to prune away variables from modifies clauses that are not needed?

Or maybe when inlining gets performed modifies clauses should not even be needed?

I can email this Boogie file if someone is interested to take a look. Unfortunately I could not attach it to this issue. Thx.

**Comment by akashlal** [comment]
Hi Zvonimir,
In case you're not doing this already, the following re-computes modsets of
procedures with implementations:

(new ModSetCollector()).DoModSetAnalysis(program);


Corral deletes the modset information in the input program and then
recomputes it when needed (i.e., before VC generation)


Akash

**Comment by zvonimir** [comment]
Thanks Akash. I have not had time to look into fixing this myself, but I just asked a student of mine who is getting familiar with Boogie (Shaobo is his name) to take a look. I hope we'll be able to propose a fix soon.

**Comment by zvonimir** [comment]
FYI, Shaobo discovered the following Boogie command line option: `/doModSetAnalysis`
This option prunes modifies clauses before inlining, which is exactly what we needed. We are good now and I am closing this issue.
