### ISSUE TITLE
Version 2.5.2 introduces false bugs it seems

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#203]
This is the regression: 
[test.zip](https://github.com/boogie-org/boogie/files/4234528/test.zip)

This is the command I use:
```
boogie test.bpl /nologo /noinfer /doModSetAnalysis /timeLimit:1200 /errorLimit:1 /loopUnroll:15
```

We had this regressions for years now, and neither Boogie nor Corral would report an error trace for it. The most recent release of Boogie (2.5.2) started to report an error trace.

**Comment by bkragl** [comment]
I cannot reproduce this. See also branch [issue-203](https://github.com/boogie-org/boogie/tree/issue-203) where I added your regression and it passes.

Interestingly, the test fails if I drop `/noinfer`, but verifies again if I decrease the bound for loop unrolling. Could it be that this test benefited (in terms of stability) from some Z3 option that Boogie was previously setting?

**Comment by zvonimir** [comment]
Ah, interestingly enough, I encountered this problem with Z3 4.8.5, and switching to Z3 4.8.7 fixes it.
However, this update leads to a bunch of issues with Corral. Kind of crazy.

**Comment by bkragl** [comment]
@zvonimir, does it make sense to merge this example into the Boogie regressions, or should I just delete the branch?

**Comment by zvonimir** [comment]
Good question. The example is pretty large, and I have no idea which feature of it caused this problem. But clearly there is something interesting about it. So I would lean towards adding it.

**Comment by bkragl** [comment]
Merged the test into master.
