### ISSUE TITLE
Make /noinfer by the default option

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#204]
I am not sure if there are users that invoke Boogie without using `/noinfer`. I've never managed to successfully leverage any of the abstract interpretation algorithms that are build into Boogie. So I think we should make `/noinfer` be the default behavior. If that is already the case, it might be good to document that.

Thoughts?

**Comment by bkragl** [comment]
In my work on CIVL, I found that sometimes abstract interpretation figures out simple loop invariants when iterating over arrays, which are needed to prove the core invariant.

```
i := 0;
while(i < n)
invariant 0 <= i && i <= n; // For example this one.
{
  ...
  i := i + 1;
}
```

But we actually always strive to have our examples verified with `/noinfer`.

**Comment by zvonimir** [comment]
Got it. To me this also says that `/noinfer` should probably be the default setting.

**Comment by shazqadeer** [comment]
I am supportive of /noinfer being the default, especially because sometimes inference takes a long time when a significant amount of inlining has been done.  

@zvonimir : Please put up a PR.  

@RustanLeino : Heads up.

**Comment by bkragl** [comment]
So the idea is that option `/noinfer` will be removed, and no abstract interpretation is performed unless requested with `/infer`, right?

**Comment by zvonimir** [comment]
Yep, that is my take on this. I got busy with Corral and so I won't be able to get to this today.

**Comment by zvonimir** [comment]
@rospoly This is a good first issue to try to resolve as you are learning Boogie.

**Comment by alexanderjsummers** [comment]
I'd also like this to be the default behaviour - we specify it from all of our tools (and typically teach students to do it when they're new to using Boogie).

**Comment by RustanLeino** [comment]
I'm late to the party. Dafny always uses -infer:j. But Dafny can turn this mode on explicitly.
