### ISSUE TITLE
Performance issues with Corral downstream

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#207]
With the recent updates to Boogie, I am seeing major performance issues with Corral downstream.
The current release of Corral seems to be using VC generation based on labels by default. My pull request https://github.com/boogie-org/corral/pull/111 switches to a more recent version of Boogie, that uses a different VC generation strategy. This seems to be causing problems in benchmarks that have quantifiers. I am seeing a major slowdown for these benchmarks with Boogie as well.

I am not sure how you would like to approach this, but it would be good to at least discuss it.

**Comment by shazqadeer** [comment]
Just so I understand your report better, are you seeing performance degradation only in problems with quantifiers?

**Comment by zvonimir** [comment]
The benchmarks are small and so I did not measure the differences precisely.
But there is obviously a class of benchmarks for which slowdowns are very large, and this is an example: [adjacent1.txt](https://github.com/boogie-org/boogie/files/4239984/adjacent1.txt)

This one goes up from 2-3 seconds (with the current Corral release) to not terminating (with this pull request https://github.com/boogie-org/corral/pull/111).

I am not sure if this is just about quantifiers, or is it about the combination of quantifiers in ensures annotations.

**Comment by akashlal** [comment]
I've not looked at this closely, but the default prover flags set by Boogie have changed. My guess would be that they are the major reason for performance degradation. The lack of labels shouldn't really make a difference. One option is to dump the prover log `/proverLog` and compare before-against-after.

**Comment by zvonimir** [comment]
Yep. So I already tried new queries with old prover flags, and that does not seem to help.
I can easily see that the lack of labels is not causing this, but I also don't think it is the different prover flags.

**Comment by zvonimir** [comment]
Ok, so when I run Z3 on the query of the current release, I get:
```
unknown
(:reason-unknown "(incomplete quantifiers)")
(labels +4 +3 +0 +1 @2 +20 +19 +17 +18 +15 +16 +13 +14 +12 +10 +11 +9 +7 +8 +5 @6 +27 +26 +21 +22 +23 +24 @25 +32 +31 +28 +29 @30 +37 +36 +33 +34 @35 +43 +42 +41 +40 +38 @39 +47 +46 +44 @45 +52 +51 +48 +49 @50 +59 +58 +57 +56 +55 +53 @54 +67 +66 +65 +63 +64 +60 +61 @62 +75 +74 +73 +71 +72 +68 +69 @70)
((0 0))
((main (- 10341)))
```

When I run Z3 on the query generated by the version from my pull request, it does not teminate.

However, when I put the old solver parameters into the new query, I get the following back:
```
unknown
(:reason-unknown "(incomplete quantifiers)")
```

I guess that the two outcomes are the same, but having labels somehow allows for Corral to generate an error trace?

**Comment by zvonimir** [comment]
I thought a bit more about this. I don't understand the concept of labels, but it seems that for some reason labels (and the information that Z3 provides about them despite also returning `unknown`) somehow allows for Corral to continue its search properly, which that does not happen when labels are not present.

So I tried a few other examples that have a bit more quantifiers using the current release of Corral, which still uses labels I believe (since it relies on an older version of Boogie). Many of them will generate queries in various iterations of Corral for which Z3 returns:
```
unknown
(:reason-unknown "(incomplete quantifiers)")
```
But this will be followed with `labels` and Corral then somehow magically (at least to me) moves on and does the right thing.

I think it would be good to first understand how come Corral works (when labels are used) despite Z3 returning `unknown`. @akashlal any thoughts on this?

**Comment by akashlal** [comment]
The `unknown` result is quite expected. Whenever you have a query with quantifiers, you are likely to get `unknown` instead of `sat` from Z3. Both Boogie and Corral treat `unknown` as `sat` and go on to query Z3 to get the (partial) model. The model usually has enough information to construct a counterexample trace.

What should I do to get a repro here?

**Comment by zvonimir** [comment]
I attached `adjacent1.txt` above, which you have to rename to `.bpl`.
The command we use is:
```
corral adjacent1.bpl /tryCTrace /noTraceOnDisk /printDataValues:1 /k:1 /useProverEvaluate /timeLimit:1200 /cex:1 /maxStaticLoopBound:1 /recursionBound:1
```

What you said above matches my observations I think. It seems that in the case of using labels, Z3 manages to return a (partial) model. When labels are not there, it seems that it fails to construct such a model.

**Comment by akashlal** [comment]
And which Z3 version are you trying?

**Comment by zvonimir** [comment]
I tried both 4.8.5 and 4.8.7 and haven't observed any differences.

**Comment by akashlal** [comment]
@zvonimir, I investigated this issue further. The master branch of corral adds the following extra flags to Z3 compared to corral on this pull request.

```
 (set-option :AUTO_CONFIG false)
 (set-option :smt.PHASE_SELECTION 0)
 (set-option :smt.RESTART_STRATEGY 0)
 (set-option :smt.RESTART_FACTOR |1.5|)
 (set-option :smt.ARITH.RANDOM_INITIAL_VALUE true)
 (set-option :smt.CASE_SPLIT 3)
 (set-option :smt.DELAY_UNITS true)
 (set-option :NNF.SK_HACK true)
 (set-option :smt.QI.EAGER_THRESHOLD 100)
 (set-option :TYPE_CHECK true)
 (set-option :smt.BV.REFLECT true)
 (set-option :smt.array.weak true)
 (set-option :smt.array.extensional false)
```

Adding these flags back should help. I did not fully integrate these flags back, but instead I just added them to the Z3 query that was getting stuck, and it makes progress now. Among these flags, the important ones are the following:

```
 (set-option :smt.array.weak true)
 (set-option :smt.array.extensional false)
```

But we should add all the ones that were there before to ensure there are no regressions in Corral. I'm guessing there is some way that corral can programmatically pass these flags to Boogie when it initializes it (`BoogieUtil.InitializeBoogie`).

One more thing, I also had to comment the following line in `Driver.cs` that was passing a flag to Boogie that doesn't exist anymore.

```
"/vc:i " +
```

**Comment by zvonimir** [comment]
Did you try this with the latest version of Boogie that does *not* use label-based VC encoding?

See this pull request that I created that updates Corral to a more recent version of Boogie: https://github.com/boogie-org/corral/pull/111

Based on what I saw (by running Corral from that pull request), putting Z3 flags back in, as you did above, helps only when label-based encoding is used. But this encoding does not exist in Boogie any more. I think that on my end Corral did not work even when I put the flags back in, which I think was due to Boogie removing label-based encoding.

**Comment by akashlal** [comment]
Yes, this was on a boogie version without labels. I have not checked this
end to end though.

**Comment by akashlal** [comment]
Let's add the extra z3 flags to this PR anyway and see where we are at.

**Comment by zvonimir** [comment]
Ah, ok, that is good news then!
Ok, I'll try to add the key flags back in later today I hope.

**Comment by zvonimir** [comment]
@akashlal I updated my pull request so that now Z3 options are being added to match the options passed to Z3 by the master branch version of Corral. I am still observing crashes (of the model cannot be found kind) and timeouts on SMACK regressions, which work with Corral from the master branch.

Any chance you could give the version from my pull request a try on your regressions/benchmarks?

**Comment by shazqadeer** [comment]
@zvonimir, @akashlal : Any updates on this issue?

**Comment by zvonimir** [comment]
New version is still slower and times out more, but I don't think there is much we can do about it. I am ok to close this.
