### ISSUE TITLE
Update SMTLIB version

### ISSUE THREAD

**Issue by dddejan** [boogie-org/boogie#217]
I was having trouble running CVC4 on some problems with datatypes. It seems like the syntax has changed, and CVC4 needs to know that the version of SMT that Boogie is using is 2.6. This should be updated here

https://github.com/boogie-org/boogie/blob/cbfeedf41e18652724798f59b799875ca286a41b/Source/Provers/SMTLib/ProverInterface.cs#L234

Note that 2.6 is the first official SMT-LIB version with datatypes.

**Comment by bkragl** [comment]
Do you think it is safe to just do this update? Meaning that Boogie already uses syntax conforming to SMT-LIB 2.6 (in general and for datatypes in particular).

**Comment by dddejan** [comment]
I think so. I manually changed the version in the SMT logs and it works just fine.

**Comment by dddejan** [comment]
Another thing I just noticed for CVC4 is that it started reported warnings for unsupported stuff. This somehow confuses the PingPong game and everything fails.

For example, if I run a log manually with CVC4 I get 

```console
cvc4 --incremental log.smt2 
log.smt2:29.23: warning: Attribute ':qid' not supported (ignoring this and all following uses)
log.smt2:30.14: warning: Attribute ':skolemid' not supported (ignoring this and all following uses)
unsat
unsat
unsat
unsat
unsat
```
which results in Boogie error:

```console
Prover error: Invalid PING response from the prover: unsat
```
I managed to get rid of this issue by adding `--quiet` as an option to CVC4. It might be a good idea to add this option by default.

**Comment by bkragl** [comment]
@dddejan, could you create a PR for setting the SMT-LIB version to 2.6? Then we can close this issue and discuss the unsupported attributes issues in #224.
