### ISSUE TITLE
Transform Function in Boogie, Trouble Understanding Documentation

### ISSUE THREAD

**Issue by rts-2** [boogie-org/boogie#226]
Hi, I'm a college student working on a semantics project for Boogie, and I'm having trouble understanding the "transform" function, as delineated here: [https://www.microsoft.com/en-us/research/wp-content/uploads/2016/12/krml178.pdf](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/12/krml178.pdf). For instance, for while loops, why put the entire rest of the function body into the while loop body? Is there a simpler explanation for Boogie somewhere?

**Comment by shazqadeer** [comment]
I did not understand your question.  Try asking again with an example, perhaps.

**Comment by shazqadeer** [comment]
Please reopen as necessary.
