### ISSUE TITLE
Unifying Monomorphize, MonomorphicArrays, and TypeEncoding.Monomorphic

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#229]
I invested some time studying parts of the code related to these options. I don't fully understand the details behind each of them, but despite that, I really don't see why we would need all 3 of them, instead of having just one, namely `TypeEncoding.Monomorphic` - which should imply both `Monomorphize` and `MonomorphicArrays` (it already does the latter).

Another thing to add is that `TypeEncoding.Monomorphic` is turned on automatically for monomorphic programs. Also, `/useArrayTheory` implies `Monomorphize` and `MonomorphicArrays`.

Any comments or feedback would be appreciated. I'll work on cleaning this up.

**Comment by zvonimir** [comment]
More exploration. Neither `TypeEncoding.Monomorphic` nor `useArrayTheory` actually work with polymorphic programs.

**Comment by shazqadeer** [comment]
I agree that we should have one option.  What should this option do?

**Comment by zvonimir** [comment]
So here is my current plan.

Options `/typeEncoding:p` and `/typeEncoding:a` stay the way they are now, but they are only applicable to polymorphic programs.

Boogie already implements and uses a check for whether a program is polymorphic or not. If the program is monomorphic, then automatically enable the monomorphic encoding (current `/typeEncoding:m`). This is already happening in Boogie automatically. If the program is polymorphic, then use one of the above encodings. Note that the current `/typeEncoding:m` does not work with polymorphic programs (Boogie crashes), and I suspect that it was not implemented for that purpose in the first place.

I think that some of the complexity of the current code, including for example the `/monomorphize` option, is an attempt to support the theory of arrays even in polymorphic programs. However, I tested this on several polymorphic programs, and when `/useArrayTheory` is enabled, Boogie crashes in various ways. So I suggest we drop support for the theory of arrays in the presence of polymorphism, which will simplify the code to some extent. There are no regressions that use that, and I would guess that even in practice nobody uses that combination (since currently it doesn't even work reliably).

So `/useArrayTheory` would require from the input program to be monomorphic, and otherwise Boogie would report an error `you cannot use array theory with polymorphic programs`.

I have started working towards what is outlined above. Thoughts?

**Comment by shazqadeer** [comment]
I suppose you are saying that the command-line option /typeEncoding:m will go away but internally the enum value corresponding to this option will remain.  

I like what you are saying for /useArrayTheory.

**Comment by shazqadeer** [comment]
Will /monomorphize also go away?

**Comment by zvonimir** [comment]
Yes, monomorphize will go away too.

**Comment by shazqadeer** [comment]
Based on your investigation, is it true that for monomorphic programs supplying /typeEncoding:m on the command-line does not make any difference?

**Comment by zvonimir** [comment]
Yes, that is true. Boogie automatically and silently sets /typeEncoding:m
when it detects a monomorphic program.

**Comment by zvonimir** [comment]
I took care of this in #234.
