### ISSUE TITLE
question: where can we find the best available language reference?

### ISSUE THREAD

**Issue by yxliang01** [boogie-org/boogie#230]
The official language reference suggests that it is very out-of-date. I think it should also tell us where we can find the best available language reference (e.g. maybe a paper?) or tell us that an up-to-date manual is still a TODO. As a result, I am unsure where we can find the best available language reference.

Thanks

**Comment by zvonimir** [comment]
Unfortunately, there is no one "best available language reference" for Boogie.
I think that "This is Boogie 2" is still the best language reference for beginners. Once you get comfortable with the basics, you can study the incomplete language reference that is linked as well. You can also ask here about the more advanced language features.
At some point someone should probably write a new language reference manual, but this is unlikely to happen any time soon given that we are all busy with other things.
