### ISSUE TITLE
Boogie source code formatting

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#237]
It occasionally really bugs me how Boogie source code formatting is all over the place.

I think that Boogie traditionally went with this style:
```
if (...)
{

}
else
{

}
```

However, now there are also (large) code sections written using this style:
```
if (...) {

} else {

}
```

Which one should we be using?

Is there a good way to reformat the whole code base without losing nice git history/blame/diff functionality?

**Comment by shazqadeer** [comment]
In addition, indentation is inconsistent.  In some files, it is two spaces and in others it is four.

**Comment by zvonimir** [comment]
There is this tool that seems should be easy to add: https://github.com/DotNetAnalyzers/StyleCopAnalyzers
