### ISSUE TITLE
Inconsistency in solution: z3 formula vs Boogie VCExpr

### ISSUE THREAD

**Issue by stanlysamuel** [boogie-org/boogie#243]
Hi all,

I use Boogie's Verification Condition engine as part of my research. I found a formula that z3 can solve but not Boogie. This seems very unintuitive to me, since Boogie invokes z3 under the hood.

Consider the formula (say VC) consisting of a free variable 's' and a bound variable 's@0' of Integer sort:

```
( Forall s@0::
    (And
        (Implies (== s 2)
            (Implies (== s@0 4) (!= s@0 5))
        )
        (Implies (!= s 2)
            (Implies (== s@0 s) (!= s@0 5))
        )
    )
)
```
It is easy to see that VC is equivalent to the formula below:

`(!= s 5)`

However Boogie is unable to prove this equivalence (due to the inability of being able to prove `(Implies VC (!= s 5))`) whereas z3 is able to prove it.

Here are the formulae in z3 and Boogie formats for reference.

**Z3:**

```
; Validity Check

(declare-const s Int)

(assert (not 
            (= 
              (not (= s 5))
                    
              (forall ((s0 Int)) 
                  (and  (=> (= s 2) 
                            (=> (= s0 4) (not (= s0 5)))
                        )
                         (=> (not (= s 2)) 
                              (=> (= s0 s) (not (= s0 5))) 
                         )                            
                    ) 
               )
          ) 
        ) 
      )
(check-sat)
```
**Boogie VCExpr:**

```
       // Added in BeginCheck() function in VC.cs
        VCExprVar s = exprGen.Variable("s", Microsoft.Boogie.Type.Int);
        VCExprVar s0 = exprGen.Variable("s@0", Microsoft.Boogie.Type.Int);
        VCExpr five = exprGen.Integer(BigNum.FromInt(5));
        VCExpr sne5 = exprGen.Neq(s,five);
        VCExpr s0ne5 = exprGen.Neq(s0,five);
        
        VCExpr four = exprGen.Integer(BigNum.FromInt(4));
        VCExpr two = exprGen.Integer(BigNum.FromInt(2));

        VCExpr s0s = exprGen.Eq(s0,s);
        VCExpr s04 = exprGen.Eq(s0,four);
        VCExpr s2 = exprGen.Eq(s,two);
        VCExpr ns2 = exprGen.Neq(s,two);

        VCExpr VC_ = exprGen.And(
        exprGen.Implies(s2,exprGen.Implies(s04,s0ne5)),
        exprGen.Implies(ns2,exprGen.Implies(s0s,s0ne5)));

        //Quantify VC_ over s@0
        var vcbinds = new List<VCExprVar>();
        vcbinds.Add(s0);
        VCExpr VC = exprGen.Forall(vcbinds,new List<VCTrigger>(),VC_);

        VCExpr test = exprGen.Eq(sne5,VC);    
        checker.BeginCheck(desc, test, reporter);
```
This is what is returned by Boogie for the above code with the `/proverOpt:VERBOSITY` option set:

```
[SMT-OUT-0] unknown
[SMT-OUT-0] (:reason-unknown "(incomplete quantifiers)")
```
whereas `[SMT-OUT-0] unsat` is expected, since Boogie checks for validity of formulae (as experimented with other formulae).

I am not clear why this happens. Am I missing something? Is there some intermediate step that Boogie does that cause this issue?

Thanks!

**Comment by stanlysamuel** [comment]
For full disclosure, the error is in reality:

```
[SMT-OUT-0] unknown
[SMT-OUT-0] (:reason-unknown "(incomplete quantifiers)")
[SMT-OUT-0] (error "line 24 column 28: unknown function/constant ControlFlow")
Prover error: line 24 column 28: unknown function/constant ControlFlow
```
and Boogie loops forever.

This brings up the question about the semantics of the ControlFlowFunctionApplication construct in Boogie VCExpr (which, if I'm not mistaken , was introduced a few months back; I couldn't see it in the earlier versions of Boogie VCExpr). I intuitively understand what it means though. For example, `(== (ControlFlow 0 34) 67)` intuitively denotes an edge from a basic block numbered 34 to the one numbered 67, in Boogie's Internal Representation. But I do not fully understand how to use it in a Boogie VCExpr.

So to eliminate the error `(error "line 24 column 28: unknown function/constant ControlFlow")` (as a hack), I can add a dummy expression `(Implies (== (ControlFlow 0 0) 0) test)` to the previous code as follows (where 'test' is defined in the previous code):

```
VCExpr controlFlowFunctionAppl = exprGen.ControlFlowFunctionApplication(exprGen.Integer(BigNum.ZERO), exprGen.Integer(BigNum.ZERO));
VCExpr cfExpr = exprGen.Eq(controlFlowFunctionAppl, exprGen.Integer(BigNum.ZERO));
VCExpr final = exprGen.Implies(cfExpr, test);
checker.BeginCheck(desc, final, reporter);
```

However, now the output is as follows:

```
[SMT-OUT-0] unknown
[SMT-OUT-0] (:reason-unknown "(incomplete quantifiers)")
[SMT-OUT-0] (((ControlFlow 0 0) 0))
[SMT-OUT-0] (((ControlFlow 0 0) 0))
[SMT-OUT-0] (((ControlFlow 0 0) 0))
...
```

and loops.

I really do not understand this behaviour of z3 in the context of Boogie. It would be great if someone can shed some light into this.

Nevertheless, irrespective of the presence of ControlFlow variables, I still think that the output should begin with `[SMT-OUT-0] unsat` because z3 is able to solve the formula on its own. This is affirmed from the fact that the implication `(Implies (!= s 5) VC)` is easily solved by both z3 and Boogie, even without ControlFlow variables as seen below:

```
[SMT-OUT-0] unsat

Verifying wp ...
  [0.112 s, 1 proof obligation]  verified
```

Thanks again.

**Comment by shazqadeer** [comment]
You are trying to Boogie in a way that was never intended.  Boogie was intended to be used by providing a Boogie text file or 
 perhaps a Boogie AST (some sophisticated tools do that). VCExpr's are a private detail of  Boogie, constructed carefully via a algorithm commonly known as verification-condition generation.  It is not expected that users or clients directly construct VCExpr's.

Your intuition about ControlFlow  is correct.  It is used by the aforementioned verification condition generator to encode the control flow in a Boogie program.

Hope that helps.

**Comment by stanlysamuel** [comment]
Thanks @shazqadeer . I agree that this is not the way Boogie should be used but I was looking for an efficient weakest precondition (or VC) generator, which is why I was looking into VCExpr's. Any leads for Boogie alternatives, off the top of your head (for efficient weakest precondition generation), would be appreciated.

Thank you once again.
