### ISSUE TITLE
/vcsCores intermixes model output

### ISSUE THREAD

**Issue by wrwg** [boogie-org/boogie#244]
The `/vcsCores` flag can dramatically speed up operation on multicore machines (e.g. my '19 MacBook pro has 8 and can easily spare 4), specifically because z3's memory usage is relative low. Unfortunately, it appears when using this option model output from different vc runs is intermixed. E.g. one output in such a situation:

```
*** MODEL
*** MODEL
...
  else -> |T@[Int]$Value!val!1|
}
Store_[$Location]$bool -> {
}
  |T@[$Location]Bool!val!1| ($Global ($StructType T@$TypeName!val!28 ($TypeValueArray |T@[Int]$TypeValue!val!0| 0) ($TypeValueArray |T@[Int]$TypeValue!val!18| 1)) 20) true -> |T@[$Location]Bool!val!3|
  else -> |T@[$Location]Bool!val!3|
}
...
*** END_MODEL
*** END_MODEL
```

This makes this flag impossible to use for tools which parse the model output. 

Is there a way to avoid this? Or does it need to be fixed?

@shazqadeer

**Comment by shazqadeer** [comment]
I agree this is a problem.  There is the following option for printing the model to a file.

/printModelToFile:<file>
                print model to <file> instead of console

However, most likely the contents of the file will also get garbled if all threads are writing the models to the same file.  

One option might be to specify the model output file name via an attribute on an implementation.  If this file name is supplied, the model can be written to that file.  The client is responsible for making sure that there is a distinct file name on each implementation.

By the way, in addition to the model, wouldn't the same problem happen for counterexample traces?

**Comment by wrwg** [comment]
Yes, the same would apply for execution traces.

Do you say there is an attribute which can be added fo procedures where to write the model to? Which would that be?

**Comment by shazqadeer** [comment]
#258 should fix this issue.  I will wait to hear back before closing this issue.

**Comment by shazqadeer** [comment]
I will close this issue.  But please reopen if the problem persists.
