### ISSUE TITLE
Error: No input files were specified when mono Binaries/Boogie.exe

### ISSUE THREAD

**Issue by YueWang1996** [boogie-org/boogie#249]
Hello, I am trying to run Boogie but meet this error.

**Environment**
Ubuntu 18.04+mono
Z3

**Successful steps(installation+build)**
`$ dotnet tool install --global boogie`
`$ nuget restore Source/Boogie.sln`
`$ msbuild Source/Boogie.sln`

**Error**
`yue@ubuntu:~/boogie$ mono Binaries/Boogie.exe`
`*** Error: No input files were specified.`

Sorry that I m not that familiar with how mono works. I am not sure whether it is the right way to run Boogie.
I would appreciate it if you could give me any hints about the solution to this bug. Thanks for the help!

**Comment by stanlysamuel** [comment]
You missed the Boogie input file (in .bpl).

`mono Binaries/Boogie.exe <.bpl file> ` is right.

**Comment by YueWang1996** [comment]
> You missed the Boogie input file (in .bpl).
> 
> `mono Binaries/Boogie.exe <.bpl file> ` is right.

It works. Thanks a lot!
