### ISSUE TITLE
Syntax of floating-point models

### ISSUE THREAD

**Issue by shaobo-he** [boogie-org/boogie#256]
It seems floating-point models are not printed in ``a more human readable'' way when the option is `/printModel:4`. For example, we have error models printed like `a -> (fp 0bv1 127bv8 0bv23)` and `a -> (_ (+zero) 8 24)`, which correspond to 1.0 and 0.0. I would propose we print floating-point models as Boogie constants as the latter are supposed to be more human readable.

**Comment by zvonimir** [comment]
Good suggestion.

When we run Corral on a floating-point Boogie program, how are values of floating-point variables printed in the trace?

Also, I forgot, but how do we specify floating-point constants in Boogie programs? I remember Rustan wrote a long post about what the syntax of floating-point constants should be.

Basically, I think that how we print constants in error traces and models should match the input syntax.

**Comment by shaobo-he** [comment]
> When we run Corral on a floating-point Boogie program, how are values of floating-point variables printed in the trace?

They are printed as Boogie floating-point literals.

> Also, I forgot, but how do we specify floating-point constants in Boogie programs? I remember Rustan wrote a long post about what the syntax of floating-point constants should be.

IIRC, the current syntax of Boogie floating-point literals is what Rustan proposed.

> Basically, I think that how we print constants in error traces and models should match the input syntax.

Yes, I should look into it.

**Comment by shazqadeer** [comment]
@shaobo-he , @zvonimir : Is one of you going to put up a PR to close this issue?

**Comment by shaobo-he** [comment]
> @shaobo-he , @zvonimir : Is one of you going to put up a PR to close this issue?

I don't have a plan.

**Comment by shazqadeer** [comment]
/printModel had many unused parameters.  Now /printModel supports only 0 and  1.  So the lack of support for "enhanced error messages" is official.  I am closing this issue.  However, I would welcome a PR to improve the display of floating-point literals if there is need for it.
