### ISSUE TITLE
Make Z3 4.4.1 the recommended version?

### ISSUE THREAD

**Issue by wuestholz** [boogie-org/boogie#26]
Is there any reason for not making Z3 4.4.1 the recommended version? There are just minor differences in the output of two test cases (livevars/daytona_bug2_ioctl_example_2.bpl and test15/CaptureState.bpl). In one case the model is slightly different and in the other case the trace is slightly different (for a STORM-generated file that supposedly has quite some non-determinism due to thread interleavings).

**Comment by delcypher** [comment]
@wuestholz +1 for moving to a newer version of Z3. There is one minor blocker right now which is I need to package a newer version of Z3 to use for the TravisCI build. I need to do this for a few other projects of mine as well so I'll be doing this quite soon.

**Comment by wuestholz** [comment]
Great! I would do the same for the Jenkins build server once we have updated the expected outputs of the test cases.

**Comment by delcypher** [comment]
@wuestholz Great. Could you make a branch for the test changes required for Z3 4.4.1? we can then each do our own local testing and when we are ready to make the switch we can merge the branch into master.

**Comment by wuestholz** [comment]
Sure. I have created the branch and I committed the changes to the test output.

**Comment by delcypher** [comment]
@wuestholz Just to let you know I am working on this.
I'm waiting for two PRs to merged into Z3 that fix various packaging problems.

https://github.com/Z3Prover/z3/pull/338

https://github.com/Z3Prover/z3/pull/340

Hopefully they will be accepted and then another release can be made so I can package it up.

**Comment by delcypher** [comment]
#27 implements this.
