### ISSUE TITLE
Output: Boogie program verifier finished with 0 verified, 0 errors

### ISSUE THREAD

**Issue by YueWang1996** [boogie-org/boogie#260]
Hello, I successfully run Boogie on my machine.
**Environment**
Ubuntu 18.04+mono
Z3

**Question**
When I try to run a .bpl file which contains many types, axioms, functions, and procedures(please see attached file) , 
I meet this result:
`yue@ubuntu:~/TAP/SGX$ mono ~/boogie/Binaries/Boogie.exe sgx_type.bpl `
`Boogie program verifier version 2.4.1.10503, Copyright (c) 2003-2014, Microsoft.`

`Boogie program verifier finished with 0 verified, 0 errors`

Actually, there are many procedures that could be verified in the file. Codes in the file are created by others and have been verified to work correctly. So I am confused by this result. I think I should get a result saying "finished with xx verified, 0 errors".

Could you please give me any hints about the possible problem? 
Thanks for the help!

**Code of the sgx_type.bpl file**
[sgx_type.txt](https://github.com/boogie-org/boogie/files/4941938/sgx_type.txt)

**Comment by shazqadeer** [comment]
All the procedures in your input file are decorated with {:inline 1} attribute.  This indicates to Boogie that these procedures should be inlined at their call sites.  Boogie does not verify such inlined procedures instead delegating their verification to their callers.  You should either removed the inlined attribute or add non-inlined procedures that call these inlined procedures to get verification done.
