### ISSUE TITLE
.NET framework solution does not build on master

### ISSUE THREAD

**Issue by keyboardDrummer** [boogie-org/boogie#270]
When I try to build the .NET framework solution on master, every project fails to build with errors like the following:
```
Source\CodeContractsExtender\obj\Debug\AssemblyInfo_CodeContractsExtender_o3epbmkj.5cl.g.cs(11,12,11,31): error CS0579: Duplicate 'AssemblyFileVersion' attribute
Source\CodeContractsExtender\obj\Debug\AssemblyInfo_CodeContractsExtender_o3epbmkj.5cl.g.cs(12,12,12,27): error CS0579: Duplicate 'AssemblyVersion' attribute
```
I'm not sure at which commit this problem is introduced, but switching to an old tag like `v2.4.2` resolves the issue, and I am able to build then.

Judging by the [travis file](https://github.com/boogie-org/boogie/blob/master/.travis.yml), Boogie is not building its .NET framework solution on the build server. Is that correct?

I feel we should either remove the .NET framework solution/project files, or build it in the build-server as well.

**Comment by bkragl** [comment]
The two builds (.NET Core and .NET Framework) somehow interfere with each other, see #190. So it is not possible to have both builds in the same directory. If you want to switch from one build to the other, it's best to remove all generated files (e.g., using `git clean -dfx`).

> I feel we should either remove the .NET framework solution/project files, or build it in the build-server as well.

I think the current understanding is that the .NET Framework build will be removed eventually. Unfortunately there are still Boogie clients that currently need the old build.

**Comment by keyboardDrummer** [comment]
> The two builds (.NET Core and .NET Framework) somehow interfere with each other, see #190. So it is not possible to have both builds in the same directory. If you want to switch from one build to the other, it's best to remove all generated files (e.g., using git clean -dfx).

Yes but I'm failing to build .NET framework on master with a fresh folder.

**Comment by bkragl** [comment]
Hmm, what is your setup? I just built the current master (v2.7.9) on an Ubuntu machine as follows:

```
nuget restore Source/Boogie.sln
msbuild Source/Boogie.sln
```

> Also, which clients still need .NET framework support? I know of Dafny. I can look into what's required to move that to .NET Core.

See [here](https://github.com/boogie-org/boogie/issues/190#issuecomment-658535280). I think in this case it is not the tool (Corral already runs under .NET Core), but the machines it is running on. My expectation is that this will resolve over time.
