### ISSUE TITLE
ModelViewer and BVD projects

### ISSUE THREAD

**Issue by shazqadeer** [boogie-org/boogie#293]
@RustanLeino, @gauravpartha, @michalmoskal, @shuvendu-lahiri:

There are two projects, ModelViewer and BVD, that are currently not built with Boogie-Netcore.sln.  The code in these projects is relevant to visualization of models (returned by the SMT solver and processed into an instance of Microsoft.Boogie.Model) from the lens of the client language that compiles to Boogie for verification.  I would like to delete this code from the Boogie repository because (1) it is not being maintained, and (2) it appears to belong clients of Boogie rather than Boogie itself.  Any objections?

**Comment by gauravpartha** [comment]
Fine from the Viper side, thanks for asking. We use the "/mv" option to obtain models from Boogie, but we don't seem to make use of the ModelViewer/BVD projects.

**Comment by mmoskal** [comment]
I surely have no strong opinions here. Thanks for checking though!

**Comment by shazqadeer** [comment]
Adding @zvonimir and @bkragl for their opinions also.

**Comment by shazqadeer** [comment]
@gauravpartha: I am glad that you responded and mentioned that you use /mv feature in Boogie.  I was not aware of any users.  I have put up PR #292  for an augmented trace feature that outputs data values.  I am wondering if there is overlap in the functionality of my PR and the /mv feature.  I have never used the /mv feature myself.

**Comment by shazqadeer** [comment]
To educate myself, I looked at the implementation of the ModelViewInfo feature in Boogie.  There is definitely overlap between this feature and PR #292 in the part related to examination of data values.  The main difference is that ModelViewInfo feature aims to provide the user with the entire state visible in the Boogie procedure at the state capture point (indicated by :captureState), whereas PR #292 aims to print only specific variables indicated by the user at the capture point (indicated by :debug).  PR #292 also has an explicit goal of capturing custom error traces that have source information from the program that was compiled to Boogie.  I suppose this goal could be met indirectly by naming the captured states in ModelViewInfo feature appropriately.

The implementation of ModelViewInfo feature is not robust.  It depends on the assumption that the solver is parsimonious in bindings of the model for an uninterpreted function, i.e., it does not provide bindings that are unnecessary to justify the "path" taken in the Boogie program.   It is possible to fix the robustness issue.  But I am curious to know if the ModelViewInfo feature is being used seriously.  Would the functionality provided by PR #292 be adequate instead?

**Comment by gauravpartha** [comment]
> The implementation of ModelViewInfo feature is not robust. It depends on the assumption that the solver is parsimonious in bindings of the model for an uninterpreted function, i.e., it does not provide bindings that are unnecessary to justify the "path" taken in the Boogie program. It is possible to fix the robustness issue. But I am curious to know if the ModelViewInfo feature is being used seriously. Would the functionality provided by PR #292 be adequate instead?

I don't think PR #292 in its current form would be adequate for our use of /mv. @marcoeilers implemented a feature in the Viper backends that prints for each Viper failure the corresponding counterexample. Traces are currently ignored (i.e., the corresponding control variables are not translated to a Viper trace), the focus is on the values of each of the Viper variables in the counterexample at the point where the failure happens. So, we require for each Boogie failure the corresponding complete counterexample. We don't output any "captureState" attributes in the Boogie encoding.

As a side remark: @marcoeilers tried to use the /printModel feature first instead of /mv, but it behaved strangely when there were multiple errors (the order of the models was not as expected). Moreover the promised reverse translation by "/printModel:2" did not seem to work (hence we must back-translate the SMT variables ourselves to the original Boogie variables), but we might have misunderstood the documentation.

**Comment by RustanLeino** [comment]
Dafny emits `{:CaptureState}` attributes. These had been used in the Dafny plug-in for the Boogie Verification Debugger (BVD). The now deprecated IDE for Dafny in Microsoft Visual Studio built in easy access to BVD. However, the currently supported IDEs for Dafny (VS Code, emacs, ...) do not make use of BVD.

In conclusion, Dafny is no longer making use of BVD. Therefore, the `{:CaptureState}` attributes it generates are also not used by anything.

**Comment by shazqadeer** [comment]
> As a side remark: @marcoeilers tried to use the /printModel feature first instead of /mv, but it behaved strangely when there were multiple errors (the order of the models was not as expected). 

This problem has been fixed in master.

> Moreover the promised reverse translation by "/printModel:2" did not seem to work (hence we must back-translate the SMT variables ourselves to the original Boogie variables), but we might have misunderstood the documentation.

There does not appear to be any difference in Boogie's behavior across different nonzero arguments to /printModel;  they are all treated the same.  Plus, I have no idea what reverse mappings mean.  So, I am planning to disallow an argument other than 1 and clean up the documentation.

> I don't think PR #292 in its current form would be adequate for our use of /mv. @marcoeilers implemented a feature in the Viper backends that prints for each Viper failure the corresponding counterexample. Traces are currently ignored (i.e., the corresponding control variables are not translated to a Viper trace), the focus is on the values of each of the Viper variables in the counterexample at the point where the failure happens. So, we require for each Boogie failure the corresponding complete counterexample. We don't output any "captureState" attributes in the Boogie encoding.

There is contradictory information in the comment above.  As far as I understand /mv command-line option and :captureState attribute have to be used together.  If you are not using :captureState then /mv will not give you any useful information.  So, the question remains:  are you using this feature or not?

**Comment by shazqadeer** [comment]
Regarding the original issue I raised about eliminating ModelViewer and BVD projects, it looks like nobody is fighting to keep them in the repository.  So I am going to remove them.  Of course, the code can be resurrected and moved into Boogie clients when needed.

**Comment by gauravpartha** [comment]
> > I don't think PR #292 in its current form would be adequate for our use of /mv. @marcoeilers implemented a feature in the Viper backends that prints for each Viper failure the corresponding counterexample. Traces are currently ignored (i.e., the corresponding control variables are not translated to a Viper trace), the focus is on the values of each of the Viper variables in the counterexample at the point where the failure happens. So, we require for each Boogie failure the corresponding complete counterexample. We don't output any "captureState" attributes in the Boogie encoding.
> 
> There is contradictory information in the comment above. As far as I understand /mv command-line option and :captureState attribute have to be used together. If you are not using :captureState then /mv will not give you any useful information. So, the question remains: are you using this feature or not?

When one uses the /mv option without any captureState attributes, a Z3 model is printed for each error. So in practice not providing "captureState" attributes still gives a meaningful output. The fact that this happens might be a coincidence, I don't know. As I mentioned, the reason we use /mv instead of /printModel is that the order seemed to be not as expected in /printModel (we are currently using an older version of Boogie but should be upgrading soon). However, since you said that the /printModel issue has been resolved, we could try to use printModel instead which in theory would be sufficient for us.

**Comment by shazqadeer** [comment]
Thanks for the explanation.  If you use /mv, it enables model printing internally.  Using /mv without captureState is essentially identical to using /printModel:n for n > 0.

**Comment by fabianhauser** [comment]
As far as I see, the Dafny VSCode-Plugin currently uses the BVD model resp. the  `/mv`-call to provide the user with a counter-example. (This is done here: https://github.com/dafny-lang/dafny/blob/master/Source/DafnyServer/DafnyHelper.cs#L113)

**Comment by shazqadeer** [comment]
@fabianhauser : I am wondering if Dafny is using /mv: in the same way that Viper is using it, i.e., to print out the model.  Would it  be possible  for you to double check that? As I indicated above, model printing should work fine with /printModel:n which prints the model corresponding to a counterexample right after the counterexample.
