### ISSUE TITLE
Framework build broken

### ISSUE THREAD

**Issue by akashlal** [boogie-org/boogie#303]
I am unable to build Boogie via `Boogie.sln`. I get several errors. It seems that the build for Framework is broken and it has been broken for a while. Perhaps the writing is on the wall to drop the Framework build and switch exclusively to .net core? The same will hold for corral as well then.

**Comment by bkragl** [comment]
In principle, it should not be too difficult to fix the Framework build (by adding missing `.cs` files to the `.csproj` files and rewriting the lines of code that use features only available in .NET Core). However, I think that it would be best for the future if we can eliminate the Framework build and switch exclusively to .NET Core. I believe the main reason this was not done yet was Corral's requirement to still support Framework. If this is not the case anymore, I think we can drop the Framework build.

@akashlal, if you want, I'd be happy to put up a PR in Corral that removes the Boogie submodule and instead references the Boogie package (I just tried locally and it worked).

**Comment by akashlal** [comment]
Thanks @bkragl. Please do open a PR for Corral. I think switching exclusively to `core` is the path forward.
