### ISSUE TITLE
polyhedra for linear inequalities not supported for abstract interpretation?

### ISSUE THREAD

**Issue by shaobo-he** [boogie-org/boogie#31]
Hi,

I tried to invoke boogie with flag `/infer:p` while got an error message saying argument `'p'` is not valid. I was wondering if it is still supported while the help message is not updated.

Thanks,
Shaobo

**Comment by shazqadeer** [comment]
@RustanLeino : This should be a quick one to close for you.

**Comment by shazqadeer** [comment]
I just looked at the help message:

i = intervals
                   c = constant propagation
                   d = dynamic type
                   n = nullness
                   p = polyhedra for linear inequalities

I see that the above options are not supported by the parsing of /infer flag.  

@RustanLeino :  Could it be that support for the above options was dropped at some point but help was not updated?

**Comment by bkragl** [comment]
It looks like there are two implementations of abstract interpretation in the Boogie codebase.

Project `AbsInt` implements the currently supported domains:
t = trivial bottom/top lattice
j = intervals (used to be called "strong intervals" to distinguish it from i)

Project `AIFramework` is currently not used anywhere, but seems to contain code for the other domains mentioned above.

PR #219 updates the help message to reflect the currently supported flags.

**Comment by shazqadeer** [comment]
AIFramework is not part of the Boogie.sln.  Anybody know why?
