### ISSUE TITLE
Status of FixedPointVC (cleanup)

### ISSUE THREAD

**Issue by akashlal** [boogie-org/boogie#338]
Boogie has a VC generation algorithm called `FixedpointVC`. It implements the interpolation-based duality algorithm. Is anyone using or experimenting with it? There are no associated tests. I fear that if no one is using it, then its probably in a broken state already. We should remove it and clean up the code, unless someone wishes to maintain it.

This option is exposed via Corral as well, so I will ask Corral users the same question.

**Comment by shazqadeer** [comment]
The status of FixedPointVC is similar to StratifiedVC, i.e., it is a library that is consumed by Corral.  From Boogie's point of view, it is ok to not have tests for it in Boogie if Corral devs agree to maintain the library and have appropriate tests in Corral for it.  If support for interpolation is dropped in Corral itself, then there is little point keeping the library around in Boogie.

**Comment by shazqadeer** [comment]
The discussion has shifted here:  https://github.com/boogie-org/corral/issues/136.  So I  am closing this issue.
