### ISSUE TITLE
Dropping sk_hack regression test

### ISSUE THREAD

**Issue by shazqadeer** [boogie-org/boogie#343]
Is the following test still relevant?

https://github.com/boogie-org/boogie/blob/master/Test/test2/sk_hack.bpl

I would like to drop it because I don't want Boogie to depend on esoteric features of Z3.

@RustanLeino , @michalmoskal :  Do you have any concerns?

**Comment by RustanLeino** [comment]
No concerns from my side. I recently dropped this option from Dafny, and Dafny's test suite was still fine.
