### ISSUE TITLE
z3Exe flag seems to have stopped working.

### ISSUE THREAD

**Issue by bobismijnnaam** [boogie-org/boogie#349]
In VerCors we call carbon by supplying an explicit path to z3:

```scala
class CarbonVerifier[O](o:OriginFactory[O]) extends SilverImplementation[O](o) {
  override def createVerifier(tool_home:Path,settings:Properties):viper.silver.verifier.Verifier = {
    val carbon = viper.carbon.CarbonVerifier(Seq("startedBy" -> "example", "fullCmd" -> "dummy"))
    carbon.parseCommandLine(Seq(
        "--z3Exe", Configuration.getZ3Path.getAbsolutePath,
        "--boogieExe",Configuration.getBoogiePath.getAbsolutePath,
        "-"))
    carbon.start()
    carbon
  }

}
```

This seems effective enough: in the screenshot below this path appears in the call to boogie.

![image](https://user-images.githubusercontent.com/3082344/110819558-96172c00-828e-11eb-80e7-c2d4df5e1b79.png)

However, upon termination, Boogie reports it cannot find "z3" in the same folder Boogie is located in:

![image](https://user-images.githubusercontent.com/3082344/110819785-cbbc1500-828e-11eb-8226-1b3ec4ef90f9.png)

So it seems to have swapped out the path I passed for some reason. The issue is resolved when I copy the executable at the z3 path to the Boogie folder and name it "z3.exe", but we'd like to avoid that and keep the tools separate.

For what it's worth, I've looked a bit through carbon's code, and it seems to handle the presence of the flag just fine. But when I pull the carbon repository and run carbon from the command line, the same problem happens: besides adding the --z3Exe flag, z3.exe needs to be present in the boogie folder, to make verification work.

This used to work on 20.07, but after upgrading to 21.01 this broke. The boogie version we use is: "2.4.1.10503", which is the one available from the viper/ETH Zurich site. Did I miss an interface change, is this a bug, or is the boogie version we use no longer supported?

**Comment by bobismijnnaam** [comment]
Apologies, I posted this issue in the wrong repository!

**Comment by bkragl** [comment]
You seem to use a very old Boogie version. If it helps, `-z3exe` was dropped from Boogie in favor of `-proverOpt:PROVER_PATH` in https://github.com/boogie-org/boogie/pull/197.

**Comment by bobismijnnaam** [comment]
That was indeed the case! :)
