### ISSUE TITLE
Declaration conflict between quantified variables and others

### ISSUE THREAD

**Issue by shaobo-he** [boogie-org/boogie#36]
Consider the following Boogie program,

``` Boogie
procedure foo(n:int)
{
  var q : int;
  assume n > 0 ==> (forall q: int :: q > 0);
}
```

Boogie will give the following warning,
`test.bpl(4,27): Error: more than one declaration of variable name: q`

Is this behavior expected given that the second `q` is bounded by a quantifier?

**Comment by shazqadeer** [comment]
I believe this is a bug masquerading as a feature.  Not sure what the right fix is though.
