### ISSUE TITLE
Monomorphization: Can't interpret model for monomorphized values

### ISSUE THREAD

**Issue by wrwg** [boogie-org/boogie#360]
When having something like `Vec T`, Boogie creates a monomorphized representation of the form `Vec_79209` or any other arbitrary number it chooses. This makes it hard to analyzed the Z3 model because the relation to the original type is lost. It would be easier to deal with this (and read the model) if there would be a canonical mangled representation for those types, as in `Vec_@T` or such.

@shazqadeer

**Comment by shazqadeer** [comment]
I spent some time thinking about this problem and I am at a loss.   There are two requirements:

1. From Boogie side, especially Civl which depends on monomorphization, we want that the monomorphized file could be dumped out as a valid Boogie file.
2. @wrwg wants that the instantiated type name should be easily generated from the mangled name.

I can't figure out how to do this without imposing some restriction on type names in the input file.  

@bkragl , @RustanLeino :  Do you have a suggestion?

**Comment by wrwg** [comment]
Not sure whether this helps, but there are standard techniques for mangling. One I came along a while ago is (a) prefix every mangled name with `__` or similar (b) prefix every non-representable character character with something like `U` in the mangled name (b) encode those characters using the US keyboard: ! => 1, @ => 2, .., ) => 0, and a few more ad-hoc rules for those characters which do not have a special character in cap position.

For example: `a&bU` -> `__aU7bUU`

**Comment by bkragl** [comment]
I'm not sure I understand the problem. If the requirement is to generate the mangled name locally and deterministically form just the instantiation, then it is indeed not possible without a restriction on the user input. There is always the possibility that the generated name conflicts with something form the input.

A while back we changed Civl to initially compute a unique prefix (`Civl_` plus as many `_` as needed) that is prepended to every internally generated symbol. Should monomorphization do something similar? As far a I can see, the current strategy in monomorphization (appending a counter value to the name) does not satisfy the requirement of dumping a valid Boogie program. The user could declare `Vec_79209` and we get a conflict.

**Comment by shazqadeer** [comment]
Perhaps @wrwg should specify his requirement more precisely. I understood that he wants Boogie to implement a function from fully-instantiated type names to strings that is easily invertible via a simpler parsing algorithm.

**Comment by shazqadeer** [comment]
Closing this issue.
