### ISSUE TITLE
Mozilla MXR site is down - who to contact?

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#37]
I am kind of hoping that @delcypher would know the answer to this :).
Basically, this does not work

```
mozroots --import --sync
```

since the whole mxr Mozilla website seems to be down. Because of this, I am having trouble building Boogie on Linux. I just spent half an hour trying to figure out where to report this, without any success.
How should we go about this?

**Comment by delcypher** [comment]
@zvonimir 
I'm not entirely sure what the solution is here but for mono >= 3.12 [a tool is included that syncs the certificate store with the system one](http://www.mono-project.com/docs/getting-started/install/linux/#notes). Looks like the tool is called [``cert-sync``](http://www.mono-project.com/docs/faq/security/). I'd give that a try first.

**Comment by edmorley** [comment]
Mozilla's MXR site is likely not coming back (see https://bugzilla.mozilla.org/show_bug.cgi?id=1279952).

However it's worth noting that it should never have been used to pull from as part of a build/automation anyway - it's a code indexer, not a source code repository. (And particularly not over plain HTTP!)

I'm presuming this need to be fixed upstream in mozroots, wherever that is.

**Comment by zvonimir** [comment]
FYI, I just tested your suggestion @delcypher, and indeed once you switch to a later version of mono (installed from `mono-complete` package) mozroots is not needed any more and that line can be completely removed it seems.

**Comment by zvonimir** [comment]
This was resolved while back.
