### ISSUE TITLE
Implementation inlining consumes large memory

### ISSUE THREAD

**Issue by shaobo-he** [boogie-org/boogie#373]
Hello Boogie developers,

I'm observing large memory consumption of Boogie on certain programs. For the attached example, running Boogie with `boogie.exe hostfs_enc.bpl /doModSetAnalysis /noVerify` consumes over 10GB of memory on my desktop within 5 mins and over 50GB of memory on another machine. I spent some time pinpointing the part of Boogie that's responsible for it and concluded that it's probably implementation inlining:

https://github.com/boogie-org/boogie/blob/6a8429ae51d5117fc1a85240df476284b38a1d04/Source/ExecutionEngine/ExecutionEngine.cs#L508

For the attached example, inlining implementation `oe_handle_call_enclave_function` does not return before Boogie runs out of memory.

So I was wondering if there's something I can do to avoid this issue.

Thanks,
Shaobo

[hostfs_enc.zip](https://github.com/boogie-org/boogie/files/6314272/hostfs_enc.zip)

**Comment by shazqadeer** [comment]
Try using Corral.

**Comment by shaobo-he** [comment]
> Try using Corral.

Thank you for your suggestion. I think I wouldn't have created this issue if Corral outperforms Boogie for my use cases :D

**Comment by shazqadeer** [comment]
On this specific example, what is Corral's behavior?  Does it run out of memory?  Time out?

**Comment by shazqadeer** [comment]
There is no magic here, by the way.  Inlining is exponential in the worst case and if your program's call structure is deeply-nested you can easily run out of memory. To avoid inlining, you have to use procedure summaries which must be either written by a human or automatically generated using Houdini (in general, there are other approaches but with Boogie the only thing you will get out of the box is Houdini).  Houdini is already implemented in Boogie (see [here](https://github.com/boogie-org/boogie/tree/master/Test/houdini) for samples).  I believe that Corral can make use of summaries created and populated by other tools.  So you could try to use Houdini, generate summaries, and then use Corral.  This particular flow will have to be automated by you unless Corral already provides some automation for it.

@akashlal :  Please comment if you have further advice.

**Comment by akashlal** [comment]
Running Houdini (with good candidates) followed by Corral is the best option that I can recommend. Good invariants will help Corral prune away parts of the program. 

Boogie inlining perhaps hogs more memory that it should. I think that is because the Boogie AST is quite wasteful in terms of memory. For instance, I remember having a discussion with a CBMC developer (many years back). CBMC also employs procedure inlining. We concluded that CBMC is much more memory efficient than Boogie, although I cannot recall the details. Anyway, no easy solution here.

**Comment by shaobo-he** [comment]
> On this specific example, what is Corral's behavior? Does it run out of memory? Time out?

Corral runs for days without any answers on this example.

**Comment by shaobo-he** [comment]
@shazqadeer @akashlal 

Thank you for your replies. They are very helpful.

I think I kind of know why this happens. The program to verify implements C ``object-oriented'' style of function dispatch. Namely, function pointers are embedded into structures. This confuses the alias anlysis SMACK uses and we have to use all the functions that match the call site signature as targets. This could lead to SCCs in call graph and then the explosion of procedure inlining.

**Comment by shazqadeer** [comment]
Glad the feedback was helpful. I am closing the issue.  Please reopen if needed.
