### ISSUE TITLE
Yices2 binary is called yices-smt2

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#374]
When Yices2 is installed, it comes with the following binaries: `yices`, `yices-sat`, `yices-smt`, `yices-smt2`.
The one Boogie needs is called yices-smt2. Currently Boogie is invoking `yices2`, and the solver options is `Yices2`.
I suggest we either rename the solver option as `yices-smt2`, or alternatively it remains `Yices2` but we map it to `yices-smt2` being invoked.

Thoughts?

**Comment by shazqadeer** [comment]
Yices2 as the solver option and internally invoking yices-smt2 seems easier for the user.  But you have the final call on the matter.  Please put up a PR with whatever you prefer.

@RustanLeino , @bkragl :  Please speak up if you have an opinion.
