### ISSUE TITLE
Boogie reports an error while Z3 reports unsat + model

### ISSUE THREAD

**Issue by wrwg** [boogie-org/boogie#377]
I have a boogie source which does not verify though Z3 returns 'unsat' for the VC. It appears that Z3 *also* returns a model with the unsat, which may confuse Boogie.

Repo is in the attached zip file, source `a.bpl`. When generating the smt files for this example and calling z3 directly the output is:

```
...
(((ControlFlow 0 12186) 12180))
(((ControlFlow 0 12180) 12469))
(((ControlFlow 0 12469) (- 14027)))
unsat
```

There is also a file `b.bpl` in the zip which is exactly the same as `a.bpl` only with some arbitrary `assert true` added (see diff). This file verifies and if directly called with z3, only 'unsat' is returned, no model.

In case it matters, the comand line for calling boogie is:

```
boogie -doModSetAnalysis -printVerifiedProceduresCount:0 -printModel:1 -enhancedErrorMessages:1 -monomorphize -proverOpt:PROVER_PATH=/home/wrwg/bin/z3 -proverOpt:O:smt.QI.EAGER_THRESHOLD=100 -proverOpt:O:smt.QI.LAZY_THRESHOLD=100 -vcsCores:12 -proverLog:@PROC@.smt a.bpl 
```

[bug.zip](https://github.com/boogie-org/boogie/files/6337249/bug.zip)

@shazqadeer

**Comment by wrwg** [comment]
Somehow the repro was wrong, here is a zip file with an output.bpl file which show the issue.

[bug2.zip](https://github.com/boogie-org/boogie/files/6345082/bug2.zip)

**Comment by wrwg** [comment]
Alright, this still did not repro. Please try this one:

[bug3.zip](https://github.com/boogie-org/boogie/files/6345140/bug3.zip)

**Comment by shazqadeer** [comment]
This one is better.  I ran Boogie on the file and looked at the generated smt2 log.  Only one log file was generated and its name was _X_test_contains_verify.smt.  I see there are two VCs in the file (two occurrences of check-sat).  The first one is "unknown" and a model is emitted.  The second one is "unsat".  So I don't see any problems.

**Comment by wrwg** [comment]
Closing since it turned out to be a false positive by under-triggering.
