### ISSUE TITLE
Boogie on .NET 5.0 ?

### ISSUE THREAD

**Issue by DavePearce** [boogie-org/boogie#402]
I couldn't find a duplicate of this, though I figure it has been asked before.  Currently, it seems like you need `dotnet-runtime-3.1` to run Boogie on Linux.  Otherwise, you end up with an error message like this:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.7 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

It seems to me that modern Linux distro's support .NET 5.0 and it seems to generally be the default choice.  So, I'm always either manually installing `dotnet-runtime-3.1` or asking someone to do it for me.  Anyway, I don't know what the trade-offs are here.

**Comment by shazqadeer** [comment]
I think it is a good idea to move Boogie to .NET 5.0.

@RustanLeino, @zvonimir , @bkragl :  Any opinions?

**Comment by bkragl** [comment]
> I think it is a good idea to move Boogie to .NET 5.0.

I agree. I've put up at PR.

**Comment by DavePearce** [comment]
Great --- thanks!
