### ISSUE TITLE
Failing to Verify Array Copy ?

### ISSUE THREAD

**Issue by DavePearce** [boogie-org/boogie#441]
Hey,

We (myself and @utting) have this boogie code below which fails to verify for reasons unknown.  It is a significantly cutdown version of a function originally written in Whiley.  I think I've simplified it as far as I can without losing the key issue.  

I'm assuming this is a problem related to triggering, and that adding an appropriate trigger might help?  I also notice that removing `start` altogether (i.e. so we always copy from zero) and it verifies fine.

Anyhow, any thoughts would be appreciated!

```
procedure copy(src : [int]int, start : int, dest# : [int]int, length : int) returns (result : [int]int)
requires start >= 0;
requires length >= 0;
{
   var i : int;
   var dest : [int]int;
   //
   dest := dest#;
   i := 0;
   //
   while(i < length)
   invariant i >= 0;
   invariant (forall k:int :: ((0 <= k) && (k < i)) ==> (dest[k + start] == src[k + start]));
   {
      dest := dest[(i + start) := src[i + start]];
      i := i + 1;
   }
   result := dest;
}
```

**Comment by shazqadeer** [comment]
Yes, this appears to be a quantifier instantiation problem.  While proving the loop invariant inductive, the universally-quantified loop invariant at the beginning of the loop body has to be instantiated appropriately.

Writing triggers could help.  Boogie now also supports pool-based quantifier instantiation.  You can look at the samples under Test/inst/.  For example, if I modify your example as follows:

`
procedure copy(src : [int]int, start : int, dest# : [int]int, length : int) returns (result : [int]int)
requires start >= 0;
requires length >= 0;
{
   var i : int;
   var dest : [int]int;
   //
   dest := dest#;
   i := 0;
   //
   while(i < length)
   invariant i >= 0;
   invariant (forall {:pool "L"} k:int :: {:skolem_add_to_pool "L", k} ((0 <= k) && (k < i)) ==> (dest[k + start] == src[k + start]));
   {
      dest := dest[(i + start) := src[i + start]];
      i := i + 1;
   }
   result := dest;
}
`

**Comment by DavePearce** [comment]
Hey Shaz,

Thanks for confirming it is a Z3 problem.  I'm surprised though, as this seems like a pretty common type of function.  I will try out the trigger suggestions.  The issue for me is that, at the moment, I don't have support for trigger syntax in Whiley!

**Comment by shazqadeer** [comment]
@DavePearce : Just to be clear, the solution in my message is not based on triggers; rather it is based on a different scheme, called pool-based quantifier instantiation, I implemented recently.  Boogie supports triggers also and I can tell you the trigger syntax for solving your problem if you wish.  Whether you use pools or triggers, your tool Whiley will either have to generate the appropriate incantations internally in the translator to Boogie or augment the syntax so that users can add the incantations themselves.

**Comment by DavePearce** [comment]
Fair enough!  I'm just lumping it altogether into one thing.  I need to spend some time to understand the pool-based approach.

**Comment by DavePearce** [comment]
Hey Shaz,

So, I'm still thinking about this one as well and I am now wondering what the trigger syntax looks like for this example?  I tried `{ dest[k + start] }`, and various other permutations (e.g. `src[k]`) to no avail.  Do I need to change the code in some way to enable the trigger? 

Also, I'm curious how the pool syntax works with Z3?  Does it then generate triggers for Z3, or does Z3 support the pool syntax itself now?

**Comment by shazqadeer** [comment]
The trigger syntax you used is correct.  If you add the trigger, it is automatically enabled.  And your experience with the inefficacy of triggers is typical.  Indeed, the problem gets significantly worse when the correct instantiation for a bound variable needs an expression with arithmetic in it.

The pool syntax is processed by Boogie. Z3 does not understand pools.  The implementation of pool-based quantifier instantiation in Boogie does not use triggers.  Instead, it generates instances directly and attaches them to the verification condition sent to Z3.  You can see many examples of the use of pools in the folder Test/inst.

**Comment by DavePearce** [comment]
Ok, that sounds quite interesting about pools.  I will take a look at those examples, thanks!

**Comment by shazqadeer** [comment]
I am closing this issue.  Please reopen or create a fresh issue when there is something to discuss.
