### ISSUE TITLE
Is there a Trigger for this?

### ISSUE THREAD

**Issue by DavePearce** [boogie-org/boogie#451]
Hey,

I suppose this follows on from my previous question (https://github.com/boogie-org/boogie/issues/441), but I'm wondering how to get this to go through:

```
procedure test(xs:[int]int)
{
   assume (forall k:int :: xs[k-1] < xs[k]);
   //
   assert (forall i:int, j:int :: (i < j) ==> (xs[i] < xs[j]));
}
```

My initial question is: _are there triggers which will help this go through?_  I tried a bunch of stuff but without luck

And, also I'm interested in how the pool syntax would look.

**Comment by shazqadeer** [comment]
Your example needs induction.  Since instantiation will not work by itself, neither triggers nor pools will suffice.

**Comment by DavePearce** [comment]
Thanks Shaz, I was thinking that might be the case.  Its an interesting example I found, and I am looking for more like this.
