### ISSUE TITLE
Do boogie have chat group for developers or something like that?

### ISSUE THREAD

**Issue by Luweicai** [boogie-org/boogie#456]
May be a stupid question, but looking forward to seeking help for new hands.

**Comment by shazqadeer** [comment]
@Luweicai :  Interesting thought! What would you like to see?  Gitter, Discord...  You could start one and invite everybody.   I would like to hear more about what you and your team are trying to do with Boogie.

**Comment by Luweicai** [comment]
Sorry that, I am afraid that I might mislead you. I am a new head that trying to use boogie. What I want is someplace that I can ask some superficial questions about how to use that.
