### ISSUE TITLE
Logging Splits is too close to the proceeding method

### ISSUE THREAD

**Issue by robin-aws** [boogie-org/boogie#484]
(moving here from the `dafny-lang/dafny` repo on behalf of @seebees)

```
Verifying CheckWellformed$$Module.__default.MethodNameWithoutSplits ...
  [0.545 s, 12 proof obligations]  verified
    checking split 1/3, 0.00%, (cost:87114/51) ...
      --> split #1 done,  [1.836419 s] Valid
    checking split 2/3, 99.46%, (cost:237/3) ...
      --> split #2 done,  [0.441859 s] Valid
    checking split 3/3, 99.73%, (cost:237/3) ...
      --> split #3 done,  [0.818531 s] Valid

Verifying CheckWellformed$$Module.__default.MethodNameWithSplits ...
  [3.222 s, 57 proof obligations]  verified
```

By eye, the splits associate with the first method,
but I suspect that they _should_ associate with the second.
This is because I ran this with 1 CPU and there are 0 splits in the first
and 3 in the second :)

It would be nice if these were more closely alined.

```
Verifying CheckWellformed$$Module.__default.MethodNameWithoutSplits ...
  [0.545 s, 12 proof obligations]  verified

Verifying CheckWellformed$$Module.__default.MethodNameWithSplits ...
    checking split 1/3, 0.00%, (cost:87114/51) ...
      --> split #1 done,  [1.836419 s] Valid
    checking split 2/3, 99.46%, (cost:237/3) ...
      --> split #2 done,  [0.441859 s] Valid
    checking split 3/3, 99.73%, (cost:237/3) ...
      --> split #3 done,  [0.818531 s] Valid
  [3.222 s, 57 proof obligations]  verified

**Comment by shazqadeer** [comment]
I have not been able to reproduce what you report with /vcsCores:1. With /vcsCores:3, the output is thoroughly garbled though which is definitely a problem.

I noticed that the `Verifying ...` output is printed by the following line of code in ExecutionEngine.cs.
```
Options.Printer.Inform($"Verifying {implementation.VerboseName} ...", traceWriter);
```
But the `checking split ...` output is printed in SplitAndVerifyWorker.cs as follows:
```
Console.WriteLine("    checking split {1}/{2}, {3:0.00}%, {0} ...",
          split.Stats, splitIdxStr, total, 100 * provenCost / (provenCost + remainingCost));
```
One is using some special Boogie printer API called `Inform` and the other is dumping straight to Console. Perhaps that makes a difference.

I also wonder if the two prints are being executed in different tasks.

@keyboardDrummer : Any thoughts?

**Comment by RustanLeino** [comment]
Boogie already has a mechanism for "grouping" the output from various verification tasks. Evidently, this mechanism is not being used by the `checking split ...` message.

The mechanism is `ConcurrentToSequentialWriteManager`. As far as I can tell, writers under its control are already threaded through to each verification task. So, I think the fix to this Issue is simply to replace

``` c#
Console.WriteLine("    checking split {1}/{2}, {3:0.00}%, {0} ...",
```

with

``` c#
run.TraceWriter.WriteLine("    checking split {1}/{2}, {3:0.00}%, {0} ...",
```

(It's possible that many other `Console.WriteLine`'s in Boogie should be changed analogously as well.)

Do we have a repro that would allow us to test my suggested fix?

**Comment by shazqadeer** [comment]
@RustanLeino : I created this [PR](https://github.com/boogie-org/boogie/pull/630).
