### ISSUE TITLE
Dependency on System.Runtime.Caching missing on Manjaro Linux

### ISSUE THREAD

**Issue by bobismijnnaam** [boogie-org/boogie#490]
I'm on Manjaro stable, an arch-based linux distro. I have packages `dotnet-sdk` and `dotnet-runtime`, both version 6, installed. On a fresh clone of the boogie repo, if I run the following command:

```
$ dotnet build Source/Boogie.sln
```

Boogie builds just fine. However, if I then run `BoogieDriver`, I get the following exception:

```bash
$ ./Source/BoogieDriver/bin/Debug/net6.0/BoogieDriver /?
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.Boogie.ExecutionEngine' threw an exception.
 ---> System.PlatformNotSupportedException: System.Runtime.Caching is not supported on this platform.
   at System.Runtime.Caching.ObjectCache..ctor()
   at System.Runtime.Caching.MemoryCache..ctor(String name, NameValueCollection config)
   at Microsoft.Boogie.VerificationResultCache..ctor() in /home/bobe/Downloads/boogie/Source/ExecutionEngine/VerificationResultCache.cs:line 672
   at Microsoft.Boogie.ExecutionEngine..cctor() in /home/bobe/Downloads/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 413
   --- End of inner exception stack trace ---
   at Microsoft.Boogie.OnlyBoogie.Main(String[] args) in /home/bobe/Downloads/boogie/Source/BoogieDriver/BoogieDriver.cs:line 14
Afgebroken (geheugendump gemaakt)
```

After some tinkering, it works again if I change the version of System.Runtime.Caching in ExecutionEngine.csproj to the newest major version:

```
<PackageReference Include="System.Runtime.Caching" Version="6.0.0" />
```

It then builds and runs fine (at least, for the two example programs from the `Test/` dir I tried as inputs).

I am not sure how to proceed, as I am also a total newb when it comes to the C# ecosystem. Version 4.5.0 not being available on Manjaro/Arch might be a peculiarity specific to this distros? But if it doesn't hurt Boogie it might be an idea to bump the dependency version. Documenting it for the linux users might also be sufficient.

**Comment by bkragl** [comment]
Upgrading this dependency seems fine to me. My understanding is that it is used for verification result caching. Maybe somebody who knows this feature better can clarify if the tests in `Test/snapshots/` are sufficient to catch regressions, or if we also need to check for regressions in upstream tools. Can you send a PR?
