### ISSUE TITLE
PR merge privilege

### ISSUE THREAD

**Issue by shazqadeer** [boogie-org/boogie#492]
@bkragl used to have privilege to merge Boogie PRs.  But his privilege appears to have been revoked.  Any idea what caused it to happen?  Are we following some rules about who has merge privilege?

**Comment by zvonimir** [comment]
In short, I have no idea. I certainly haven't been playing with privileges. Having said that, I vaguely remember that GitHub at some point in the past year or two changed how they deal with permissions. So maybe something got messed up that way.
Either way, I would be fine to add him back.

**Comment by shazqadeer** [comment]
@bkragl :  What would you like us to do?

**Comment by bkragl** [comment]
If you can add me to the Maintain rule, that would be great.

**Comment by shazqadeer** [comment]
@keyboardDrummer :  I can't figure out how to change Bernhard's role to Maintain.  Could you please do it?

**Comment by keyboardDrummer** [comment]
> If you can add me to the Maintain rule, that would be great.

Let's do that :-)

> @keyboardDrummer : I can't figure out how to change Bernhard's role to Maintain. Could you please do it?

I don't have Admin rights for boogie so I cannot change collaborator roles. @shazqadeer I thought you were an Admin, if not I suggest we ask the admins to make you one.

If you are an admin, in the settings tab of the repository, you will see the "collaborators and team" option under "Access", here:
![image](https://user-images.githubusercontent.com/3121201/154927976-807ad6eb-7533-43a2-a8f2-c80b5c1125a5.png)

And then you can search for a user and change the role here:
![image](https://user-images.githubusercontent.com/3121201/154927823-d91557a9-1698-4c7f-9727-9d81910d7a87.png)

**Comment by shazqadeer** [comment]
I tried to navigate to that menu but when I search for @bkragl nothing pops up.  Strange!

**Comment by RustanLeino** [comment]
I don't know what could have happened. I'm not aware of any action that would have removed Bernhard. In any case, I was able to add him back (with Maintain privilege -- let me know if this ought to be something different).

**Comment by shazqadeer** [comment]
Thanks, @RustanLeino .
