### ISSUE TITLE
Support verifying a single goal with multiple checkers to measure stability

### ISSUE THREAD

**Issue by atomb** [boogie-org/boogie#494]
## Use Case

The Dafny project has a goal of improving [verification stability](https://github.com/dafny-lang/dafny/issues/1582), to help ensure that once a program has been verified once it continues to be verifiable as it evolves. One proxy for stability is the variance in resource use between different proof attempts (either using different solvers or using the same solver with different configurations). So, we would like Dafny to be able to automatically provide this variance measurement to users by optionally attempting each proof goal multiple times (each time in a different way) and reporting the results.

We expect to use Z3 resource count as the first variance metric and to vary the proof attempts by varying the Z3 random seed (or, more broadly, the Boogie random seed). In the future, comparing proof attempts by multiple solvers may be a natural next step.

## Implementation Proposal

Given that Boogie is responsible for solver invocation, it is the natural place to implement this functionality. Other clients of Boogie may also benefit from it.

The current `CheckerPool` architecture provides a convenient starting point. To compare the results produced by attempting a proof in several different ways we could:

* Fill the `CheckerPool` with one checker for each solver configuration.
* In `SplitAndVerifyWorker.DoWork`, request multiple checkers from the pool and then perform the check with each.

Two factors will complicate this a bit, however:
* **Aggregating results.** Most of the code farther up the call tree is expecting only one `Outcome`, and arguably _should_ expect only one. I propose a function for combining `Outcome` values that fails if they're inconsistent (e.g., both `Correct` and `Errors`) and a callback for reporting statistics that client code can consume as needed.
* **State and I/O** Some of the code accumulates values to instance fields that would be misleading if accumulated over multiple runs, and some of the code writes to the console or external files during the solving process. I propose that we refactor it to avoid these operations, relying on code farther up the call stack to perform I/O. The statistics callback mentioned above can also replace some of the current instance fields (such as `resourceCount`).

This issue should probably be resolved in careful coordination with [this Dafny issue](https://github.com/dafny-lang/dafny/issues/1647), which also propose some Boogie modifications, some of which will be relevant here, as well.

**Comment by keyboardDrummer** [comment]
"Z3 random seed" -> "Boogie random seed" ? ^^

**Comment by atomb** [comment]
> "Z3 random seed" -> "Boogie random seed" ? ^^

That raises a very interesting question. Does any of the randomization that Boogie does happens before calling `SplitAndVeryifyWorker.DoWork`? If so, we'd need to orchestrate multiple verification attempts elsewhere.

**Comment by keyboardDrummer** [comment]
> 



> > "Z3 random seed" -> "Boogie random seed" ? ^^
> 
> That raises a very interesting question. Does any of the randomization that Boogie does happens before calling `SplitAndVeryifyWorker.DoWork`? If so, we'd need to orchestrate multiple verification attempts elsewhere.

I think it might be okay, but if not we can also move the randomization :-) Let's just do the multiple verification where it makes sense.

**Comment by robin-aws** [comment]
+1, especially to the **State and I/O** point. That will also help make progress towards addressing issues like #460.

**Comment by shazqadeer** [comment]
I wanted to make folks interested in stable proofs aware of this awesome tool that my ex-colleague Mathieu Baudet (@ma2bd) developed:  https://github.com/facebookincubator/smt2utils.  I am able to run this tool as follows, for example:

export SMT2PROXY_NORMALIZE_SYMBOLS=true; export SMT2PROXY_LOG_PATH=logs.10.smt2; export SMT2PROXY_MAX_RANDOMIZED_SYMBOLS=1024; export SMT2PROXY_SYMBOL_RANDOMIZATION_SEED=10; dotnet /Users/shaz/Source/boogie/Source/BoogieDriver/bin/Debug/net6.0/BoogieDriver.dll /proverOpt:PROVER_PATH=/Users/shaz/Source/smt2utils/target/release/smt2proxy /proverOpt:C:print BoogieFile.bpl

A few things to note here:
- smt2proxy appears to Boogie just as another SMT2 consumer; as its name suggests, it is acting as a proxy to Z3.
- smt2proxy has the capability to normalize symbol names used in the SMT2 output being provided to Z3; this capability also extends to randomization of symbol names.

I have found that symbol name randomization is a good way to perturb SMT solvers and exhibit the butterfly effect on unstable proofs.  I use the command above (or something similar to it) to repeatedly run the proof and evaluate the mean and standard deviation of running time.  This is a good starting step to figure out whether the current proof is flaky.  It does not, by itself, help to root out the cause of the flakiness; that would require a different tool.  But once you have identified the potential problem and tried to fix it, you can re-evaluate whether the flakiness has indeed decreased.

**Comment by atomb** [comment]
This looks exceptionally useful, @shazqadeer. Thanks for pointing it out!

**Comment by keyboardDrummer** [comment]
@atomb Could you specify what API will be added to Boogie as part of this?

I was hoping we could add options to the CLI such as `-stabilityPermutations:100` and `-stabilityMaxRDS:0.2` to specify that each verification task should be ran a 100 times with different random seeds and the relative standard deviation of the verification times of each task may not exceed 20% of the mean.
