### ISSUE TITLE
Negative BV literals?

### ISSUE THREAD

**Issue by spinda** [boogie-org/boogie#499]
When I write something like `-1bv32`, Boogie complains that I'm using the `-` operator with something that's not an `int`. I can express the same value by writing the positive signed number with the same bit-pattern and relying on wraparound, but is that the best way to write negative signed fixed-width integer literals in Boogie?

**Comment by shazqadeer** [comment]
If unary negation is not natively supported on bitvectors, then I suppose you have to encode it yourself. You could try the binary negation `0 - 1bv32`. Does that work?

**Comment by shazqadeer** [comment]
Closing as resolved for now. Please reopen if you are still stuck.
