### ISSUE TITLE
Contributing to boogie

### ISSUE THREAD

**Issue by xennygrimmato** [boogie-org/boogie#50]
Hello,

I want to contribute to this project, how do I get started?

Also, is there some IRC channel where discussions happen?

**Comment by delcypher** [comment]
@xennygrimmato 

There's a [mailing list](https://mailman.ic.ac.uk/mailman/listinfo/boogie-dev) for discussions. It's not particularly active right now though. You can also raise issues on our issue tracker.

Code contributions are accepted via PRs.

If you're looking for some low hanging fruit our language documentation needs a lot of work

http://boogie-docs.readthedocs.io/en/latest/
https://github.com/boogie-org/boogie-docs

**Comment by pramodsu** [comment]
Hi, wasn't sure where to ask this, so I decided to put it here. Is there any interest in a patch which makes the line "Boogie program verifier finished with <x> verified, <y> errors." appear in green/red depending on whether y > 0? 

I use Boogie in linux along with a makefile that runs a number of different models through the and this color-coding is very helpful in seeing which files failed.

**Comment by shazqadeer** [comment]
We love contributions.  Please put up a PR.
