### ISSUE TITLE
Boogie hangs if there is no z3 on Linux

### ISSUE THREAD

**Issue by anaumchev** [boogie-org/boogie#519]
**Problem**: Boogie just hangs when executed with no command-line arguments if there is no z3 installed.
**Expected**: Boogie reports the missing dependency and terminates.

**Comment by shazqadeer** [comment]
@anaumchev : I just committed a PR that changes how Boogie invokes the SMT solver. Could you please try again and see if your problem is resolved?

**Comment by shazqadeer** [comment]
Closing for now. Please reopen if necessary.
