### ISSUE TITLE
Weird logic when dealing with Z3 options

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#53]
Recently, we observed that Boogie seems to silently drop Z3 options when they are passed to it using lower-case letters, as in `/z3opt:smt.mbqi=true`. We tracked this behavior to this interesting piece of logic that deals with Z3 options:
https://github.com/boogie-org/boogie/blob/d93c222b70ebefa01d2f25685b95b2005697c9f3/Source/Provers/SMTLib/Z3.cs#L374
It appears that the options are filtered based on whether the first character is a capital letter or not, which is very strange since Z3 options are case insensitive. For example, if Boogie is invoked with `/z3opt:SMT.mbqi=true` the option makes its way into the generated query, while if Boogie is invoked with `/z3opt:smt.mbqi=true` it is unclear what happens in that case, but the behaviors are not identical.
My hunch is that this might be legacy code that should be cleaned up, but I am not totally sure, and so help would be appreciated.

**Comment by RustanLeino** [comment]
Odd. Yes, this sounds like a good candidate for clean-up.

**Comment by shazqadeer** [comment]
@zvonimir : I recommend consolidating all cleanup related to Z3 options in one issue and closing all other issues.

**Comment by zvonimir** [comment]
Moving discussion to issue #73.
