### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by MikaelMayer** [boogie-org/boogie#535]
https://github.com/boogie-org/boogie/blob/4353489fa1394be6ac14161cd16974f48219cff4/Source/ExecutionEngine/ExecutionEngine.cs#L1012

I get a `System.Collections.Generic.KeyNotFoundException:` here., which crashes its enclosing thread.
It's certainly due to a concurrency issue, because I was doing a lot of commands
But why....?

**Comment by keyboardDrummer** [comment]
Maybe two requests used the same `requestId`, and one cleanup up that id before the other accessed it.

**Comment by MikaelMayer** [comment]
That's an interesting hypothesis, however it is probably not the case as I verified in the calling pipeline and it's generating a unique [GUID](https://blogs.siliconorchid.com/post/coding-inspiration/randomness-in-dotnet/)

**Comment by shazqadeer** [comment]
Is there a way to reproduce the error? If not and if nobody is willing to do further investigation, I am afraid I have to close this issue.
