### ISSUE TITLE
How Do I learn Boogie?

### ISSUE THREAD

**Issue by sdconsta** [boogie-org/boogie#54]
I'm interested in possibly using Boogie for a software verification project, but I'm having trouble understanding the language. I started going through the "This is Boogie 2" manual, but quickly began running into compatibility issues (yes, I did note the disclaimer in the README). But the language reference was never sufficient for me to resolve the problem. For instance, "This is Boogie 2" discusses finite type declarations using the "finite" keyword. Apparently this keyword no longer exists, but the language reference does not cover type declarations at all. So I was unable to figure out how to declare finite types.

So at the current project state, what is the quickest way to learn Boogie?

**Comment by delcypher** [comment]
@fidget324 I share your frustration with Boogie's documentation. The "This is Boogie 2" manual is terribly out of date.

This is why I started writing new documentation which is available at http://boogie-docs.readthedocs.io/en/latest/ . The source for this is at https://github.com/boogie-org/boogie-docs .

Unfortunately I never found the time to finish it but if you're already learning Boogie filling out the many holes in this documentation would be very useful.

**Comment by shazqadeer** [comment]
Closing this issue.  We understand that documentation is important.  We will continue to improve.
