### ISSUE TITLE
Allow reusing checkers when a modelViewFile is used

### ISSUE THREAD

**Issue by keyboardDrummer** [boogie-org/boogie#541]
By taking the information from a ProverContext before it is reset, we can reuse checkers also when ModelViewFile is used:
https://github.com/boogie-org/boogie/blob/831708b6005ed8ac7f72f37a691be6deee375b13/Source/VCGeneration/Checker.cs#L65

**Comment by shazqadeer** [comment]
@keyboardDrummer:

Are #540  and this issue related?

Do you understand what is required to fix these issues?

**Comment by keyboardDrummer** [comment]
This one is is resolved, sadly the issue didn't use a permalink.

The resolving PR was: https://github.com/boogie-org/boogie/pull/564. I _think_ an important line is this one: https://github.com/boogie-org/boogie/pull/564/files#diff-0bf40bf9b608bd553aa99e972cb485c0cacc74a02875c796547ede5cafa7acccR533

Which lets the model initialise strictly instead of lazily so that the ProverContext doesn't need to be kept around.
