### ISSUE TITLE
Clarify use of StratifiedVC

### ISSUE THREAD

**Issue by keyboardDrummer** [boogie-org/boogie#544]
The class `StratifiedVC` is unused in Boogie. It is used in Corral however. We should document what it can be used for.

**Comment by shazqadeer** [comment]
@akashlal :  Could you please help?

**Comment by shazqadeer** [comment]
@akashlal : Please add a paragraph of documentation in the source code so this issue could be closed.

**Comment by akashlal** [comment]
Created PR #603
