### ISSUE TITLE
/vcsLoad no longer parses non-integers

### ISSUE THREAD

**Issue by tchajed** [boogie-org/boogie#546]
In Dafny 3.5.0, `/vcsLoad:0.5` now fails with `Error: Invalid argument "0.5" to option /vcsLoad`. This seems to be due to a regression in Boogie.

I don't have the setup to run Boogie tests directly, but looking at the code I think this call is suspicious:
https://github.com/boogie-org/boogie/blob/b090548f4c5e2b444b61884fb5b17f3fadf0a12c/Source/ExecutionEngine/CommandLineOptions.cs#L1422-L1424

There's no variant of `GetNumericArgument` that takes an `Action<double>`, so I don't know how this type-checks (is C# unsoundly casting it to `Action<int>`?). From the current API of CommandLineParseState I think this is the version to use:

https://github.com/boogie-org/boogie/blob/b090548f4c5e2b444b61884fb5b17f3fadf0a12c/Source/ExecutionEngine/CommandLineParseState.cs#L308-L312

**Comment by cpitclaudel** [comment]
> There's no variant of `GetNumericArgument` that takes an `Action<double>`, so I don't know how this type-checks (is C# unsoundly casting it to `Action<int>`?).

`x: int => load = x` is a well-typed `Action<int>`; the cast happens when assigning to `load`.  The bug was introduced in 7867a2ef as a side effect of removing `ref` parameters (cc @keyboardDrummer):

```diff
         case "vcsLoad":
           double load = 0.0;
-          if (ps.GetNumericArgument(ref load))
+          if (ps.GetNumericArgument(x => load = x))
           {
```

**Comment by tchajed** [comment]
The Dafny part makes sense. Not sure if you want to go back to `ref load` to the option parsing code or add an `Action<double>` variant to `GetNumericArgument`.

I shouldn't be surprised that the interaction of specialized type implementations, type inference, and capturing a reference would lead to confusing behaviors.

**Comment by keyboardDrummer** [comment]
Thanks for reporting. I will look at fixing this. Seems like avoiding overloaded method names in this instance will help prevent bugs like this in the future.
