### ISSUE TITLE
RFC: deprecate or remove ErrorData?

### ISSUE THREAD

**Issue by atomb** [boogie-org/boogie#562]
Many of the command types in Boogie have an `ErrorData` property which is typically a `string` but in many cases allowed to be an arbitrary `object`. I also recently added a `Description` property, of type `ProofObligationDescription` to those same commands. The primary goal of this new property was to allow separate messages for failed and successful proof of a particular proof obligation. Dafny subclasses this type extensively, and may eventually extend its own subclasses to include things like the Dafny syntax of the expression leading to a particular proof obligation. The benefit I see to this approach is that the `Description` is then always guaranteed to contain at least a success and failure message, and may also contain any client-specific data that might be useful.

The question I want to raise here is this: does `ProofObligationDescription` meet the needs of everyone who's currently using `ErrorData`? And would it therefore make sense to deprecate (and eventually remove?) the `ErrorData` property?

**Comment by keyboardDrummer** [comment]
You could check https://github.com/boogie-org/corral and https://github.com/mc-imperial/gpuverify, those are the two projects that consume Boogie through the C# API that I'm aware of.

**Comment by bkragl** [comment]
Civl uses `ErrorData` extensively to provide meaningful error messages (mainly through [this helper](https://github.com/boogie-org/boogie/blob/831708b6005ed8ac7f72f37a691be6deee375b13/Source/Concurrency/CivlUtil.cs#L128)). What needs to be done to preserve these messages if `ErrorData` would be removed? (cc @shazqadeer)

**Comment by atomb** [comment]
The migration path would be to construct a subclass of [`ProofObligationDescription`](https://github.com/boogie-org/boogie/blob/master/Source/Core/ProofObligationDescription.cs) and store instances of it in the `Description` property instead of the `ErrorData` property. To retain identical functionality to what you have right now, it would be possible to create a class that just stored the string you're currently using for the message. To make things slightly nicer, you could have a different subclass for each possible type of property that Civl checks, potentially including extra metadata, with messages to use for the case of both successful and unsuccessful proof.

**Comment by keyboardDrummer** [comment]
But since Civl is part of Boogie, the migration would be done in the PR that removes ErrorData, right @atomb ?

**Comment by atomb** [comment]
I'm happy to make these changes, @shazqadeer. I think migrating Civl should be easy, and I'll make sure to include @bkragl on the reviewers list, as the one who raised that point.
