### ISSUE TITLE
`/trace` prints incorrect time for first assertion in each file

### ISSUE THREAD

**Issue by cpitclaudel** [boogie-org/boogie#565]
Boogie's `/trace` seems to include some startup/warmup cost in the time of the first implementation in each file; for example, the following program…

```
procedure m1();
implementation m1() {
  assert true;
}

procedure m2();
implementation m2() {
  assert true;
}
```

… prints this:

```
Verifying m1 ...
  [0.149 s, 1 proof obligation]  verified

Verifying m2 ...
  [0.007 s, 1 proof obligation]  verified
```

This makes it hard to reliably find performance issues in a Boogie file.

**Comment by RustanLeino** [comment]
I tried debugging this for a while. I'm afraid I'm none the wiser.

Initially, my hunch was that the extra time goes into firing up the first `Checker`. I don't have a conclusive resolution of that hunch. I've tried

``` c#
var c = checkerPool.CreateNewChecker();
c.GetReady();
checkerPool.AddChecker(c);
```

in `VerifyEachImplementation` before the loop that creates the tasks to verify the given `implementation`s. I can confirm that only one such `Checker` is being created, but this does not affect the relative verification times of `m1` and `m2`.

I then homed in on what happens in each task, measuring the time taken by various blocks of code. It seems there are several places where the verification of `m1` is spending more time than `m2` does. I was also surprised to find that the call to `SMTLibExprLineariser.ToString` in `SMTLibProcessTheoremProver.VCExpr2String` takes about 16 ms the first time it's called, but calls after that (even repeated calls after that first call) take near 0 ms.

(I'm leaving this Issue for now.)

**Comment by shazqadeer** [comment]
@RustanLeino : Thanks for digging into this issue. I am wondering if the first VC to be generated creates some data structures that are then cached. There is a lot of shared context across VCs.

@cpitclaudel : How much extra time have you seen being reported for the first VC? I am trying to understand just how much of a problem it is in debugging performance issues. If the amount of extra time is less than a sec, it does not seem important for debugging verification issues in large problems.

**Comment by cpitclaudel** [comment]
Anywhere from half a second to a few seconds. 

>  If the amount of extra time is less than a sec, it does not seem important for debugging verification issues in large problems.

Not sure: I almost never have proofs above two seconds, so half a second is pretty large.

**Comment by cpitclaudel** [comment]
I gave it a try in https://github.com/boogie-org/boogie/pull/632, but it's pretty unpolished.
