### ISSUE TITLE
Cut GitHub releases automatically when releasing

### ISSUE THREAD

**Issue by robin-aws** [boogie-org/boogie#572]
New releases of Boogie, indicated by pushing tags, are automatically pushed to Nuget by GitHub actions, which is super nice! Some consumers have been confused by the fact that there aren't corresponding GitHub releases as well, however. There used to be up until 2.8.22, and this makes it easy to not realize there are much newer versions on Nuget.

It should be very simple to publish a GH release from [this workflow](https://github.com/boogie-org/boogie/blob/master/.github/workflows/test.yml) - I set up the same thing for Dafny [here](https://github.com/dafny-lang/dafny/blob/master/.github/workflows/publish-release.yml#L67-L77), and in this case it can be published immediately rather than creating a draft, as there won't be any release notes to fill in.

**Comment by shazqadeer** [comment]
@robin-aws : Do you understand why the publication of Github releases stopped after version 2.8.22? In any case, it would be great if you resurrected that capability. Would you consider fixing the problem in the same way you fixed it for Dafny?

**Comment by robin-aws** [comment]
Hi @shazqadeer! AFAICT the releases were never automatically published in the first place. It's just that after [this PR](https://github.com/boogie-org/boogie/pull/332) the CI started publishing to nuget automatically, and I believe the maintainers stopped bothering with the manual GitHub release process. See also https://github.com/boogie-org/boogie/issues/378.

So it's not necessarily a quick fix, it's a matter of copying the extra GitHub Actions steps we have for Dafny now. Hence I can't promise I'll have the time myself in the near future. :)
