### ISSUE TITLE
Early detection of butterfly effect

### ISSUE THREAD

**Issue by shazqadeer** [boogie-org/boogie#581]
Boogie should provide robust tooling for "fuzzing" proved programs so that an unstable proof (due to butterfly effect) is revealed early potentially before verified code is checked in.

cc: @keyboardDrummer

**Comment by atomb** [comment]
The recently-added `/randomSeedIterations:n` flag is a step toward this. It'll try every verification condition `n` times, each with a different random seed (derived from the top-level random seed, `s`, which can be set with `/randomSeed:s`) and report performance in the XML output for each attempt.

This is somewhat more developed for Dafny, which emits similar information in CSV that the `dafny-reportgenerator` can consume and check that the standard deviation of resource counts doesn't exceed a certain threshold. We've been considering moving the Dafny code for CSV generation into Boogie, which would make this available to other Boogie clients.

**Comment by keyboardDrummer** [comment]
Would it be an idea to have the standard deviation check also be in Boogie? It seems that would address this issue most directly.

**Comment by shazqadeer** [comment]
I tried /randomSeedIterations on test/civl/reserve.bpl with good results.  Thanks for adding this great feature.  

I have a couple of observations. First, the names of these options is rather misleading and in fact do not do justice to the power of the new feature. When I first saw /randomSeed*, I thought "oh, they are just varying the random seed for SMT solver, this ain't gonna help me". When I read the documentation of these features,

```
/randomSeed:<n>
                Turn on randomization of the input that Boogie passes to the 
                SMT solver and turn on randomization in the SMT solver itself.
 
                Certain Boogie inputs are unstable in the sense that changes to 
                the input that preserve its meaning may cause the output to change.
                The /randomSeed option simulates meaning-preserving changes to 
                the input without requiring the user to actually make those changes.

                The /randomSeed option is implemented by renaming variables and 
                reordering declarations in the input, and by setting 
                solver options that have similar effects.

  /randomSeedIterations:<n>
                Attempt to prove each VC n times with n random seeds. If
                /randomSeed has been provided, each proof attempt will use
                a new random seed derived from this original seed. If not,
                it will implicitly use /randomSeed:0 to ensure a difference
                between iterations.
```

I realized that these options are doing a heck of a lot more. In fact, I have tried to vary the random seed in Z3 before and it does not really do much. Could we try to rename these options to something that indicates their power?

Second, in the XML file printed out, I see a lot of stuff like this 

```
<assertion file="reserve.bpl" line="72" column="5" />
        <assertion file="reserve.bpl" line="71" column="5" />
        <assertion file="reserve.bpl" line="70" column="5" />
        <assertion file="reserve.bpl" line="63" column="5" />
        <assertion file="reserve.bpl" line="62" column="5" />
        <assertion file="reserve.bpl" line="134" column="1" />
        <assertion file="reserve.bpl" line="134" column="1" />
        <assertion file="reserve.bpl" line="40" column="1" />
```
I don't understand what this stuff is for. It is not helping and is distracting me from the investigation of the time variation. Is there a way to suppress this output?

And finally, yes, it would be great to output the standard deviation of each VC also.

**Comment by shazqadeer** [comment]
Just as evidence for how well the butterfly effect is exposed on reserve.bpl, I ran with the following options:

```
/randomSeedIterations:4 /xml:foo.xml /proc:"*Malloc*"
```

and I got running times of 1, 5, 6, and 55 seconds respectively for the four iterations.

I am curious if either @keyboardDrummer or @atomb are able to reproduce this behavior on their machines.

**Comment by shazqadeer** [comment]
By the way, the next challenge is that now that we know that the proof of reserve.bpl is unstable, how do we help the programmer (myself, in this case) understand the root cause of the instability and fix it?

**Comment by atomb** [comment]
I get some similar results: 1, 5, 1, 27, and 4 seconds with `/randomSeedIterations:5`.

When it comes to helping programmers understand the issue, that's a bit part of what those `assertion` tags in the XML are for (though perhaps they should only be produced optionally). They describe, for each verification condition ("split"), which assertions it checks. By default, they're all in one big VC. But other options can break the problem down further. As the most common example, if you combine `/randomSeedIterations` with `/vcsSplitOnEveryAssert`, you can get one assertion per VC and therefore determine which assertions in your program are a) the most expensive, and b) the most unstable (widely varying). By narrowing down the problem to individual assertions, it may be easier to see what's going on, though it definitely still requires some expertise and insight.

Admittedly, looking at the XML output by hand doesn't make identifying the culprit that easy at the moment. :)

We went through a couple of different names for what's now `/randomSeedIterations` during PR review (starting with `/stabilityIterations`), but I agree that there's probably a better name. Any ideas?

**Comment by shazqadeer** [comment]
I found the following naming and organization of the options clearer.

/randomSeed:<s>
                Supply the random seed for /randomizeVC option.

/randomizeVC:<n>
                Turn on randomization of the input that Boogie passes to the 
                SMT solver and turn on randomization in the SMT solver itself.
                Attempt to randomize and prove each VC n times using the random 
                seed s provided by the option /randomSeed:<s>. If /randomSeed option 
                is not provided, s is chosen to be zero.

                Certain Boogie inputs are unstable in the sense that changes to 
                the input that preserve its meaning may cause the output to change.
                This option simulates meaning-preserving changes to the input 
                without requiring the user to actually make those changes.
                This option is implemented by renaming variables and reordering 
                declarations in the input, and by setting solver options that have 
                similar effects.

**Comment by atomb** [comment]
I think I like that organization, @shazqadeer. For backward compatibility, we could add `/randomizeVC` while still accepting `randomSeedIterations` (documented or not). I wonder whether @robin-aws or @keyboardDrummer have any thoughts.

**Comment by shazqadeer** [comment]
I would love to make progress on this issue. Only a small reorganization of the command-line arguments is needed; it should be possible to do this in a small PR. Since the feature is still quite new and only Dafny is using it, I don't think it makes sense to have backward compatibility.  We should go forward with the reorganization that makes most sense and offers most clarity for Boogie users.

@atomb already agrees with the change.

@keyboardDrummer , @robin-aws : Do you have any concerns with the proposed change?

**Comment by keyboardDrummer** [comment]
> I would love to make progress on this issue. Only a small reorganization of the command-line arguments is needed; it should be possible to do this in a small PR. Since the feature is still quite new and only Dafny is using it, I don't think it makes sense to have backward compatibility. We should go forward with the reorganization that makes most sense and offers most clarity for Boogie users.
> 
> @atomb already agrees with the change.
> 
> @keyboardDrummer , @robin-aws : Do you have any concerns with the proposed change?

No, seems great. Do I understand correctly that it runs each proof `n` times with a different seed, failing if any of the runs fails? You could also consider tracking the runtime of each run, and determining whether the variation in runtimes goes above some threshold of relative standard deviation, which would also be a sign of instability.
