### ISSUE TITLE
Prover error when using /randomSeedIterations:n

### ISSUE THREAD

**Issue by shazqadeer** [boogie-org/boogie#583]
Repro: run boogie on Test/inductive-sequentialization/PingPong.bpl as

```
path_to_boogie PingPong.bpl /randomSeedIterations:1
```

Lots of Prover errors are spewed out:

```
Prover error: line 63 column 221: unknown function/constant random1806478530@@0

Prover error: line 154 column 104: ambiguous constant reference, more than one constant with the same sort, use a qualified expression (as <symbol> <sort>) to disambiguate random413413821@@0

(0,0): Verification inconclusive (Civl_IS_choice_MAIN)
Prover error: Invalid PING response from the prover: unknown

Prover error: Invalid PING response from the prover: (:rlimit 378)

Prover error: line 178 column 221: unknown function/constant random1150535845
```

**Comment by atomb** [comment]
It seems that this comes up with `/randomSeed`, as well. Normally, `/randomSeedIterations:1` shouldn't be any different from the default mode of operation, except that it does explicitly set the random seed if it's not already set.

**Comment by keyboardDrummer** [comment]
If I use /proverLog then it creates 2 logs, the second one only contains references to certain renamed variables but not the function definitions for them, so that's why the solver is complaining. Would have to deep dive to understand why.
