### ISSUE TITLE
Coco/R for MacOS

### ISSUE THREAD

**Issue by shazqadeer** [boogie-org/boogie#584]
I intend to add syntactic support for datatype path access in Boogie expression syntax. I will need to make changes to BoogiePL.atg and then use Coco/R to generate Scanner.cs and Parser.cs. I am doing my development on MacOS. I couldn't find an executable for Coco/R for MacOS.  I am posting this issue in case somebody can help.

**Comment by keyboardDrummer** [comment]
Have you tried `dotnet install tool` in the Boogie repository? Coco is configured as a .NET tool there: https://github.com/boogie-org/boogie/blob/master/dotnet-tools.json

**Comment by shazqadeer** [comment]
Thanks.

**Comment by shazqadeer** [comment]
When I tried to install coco on a different Mac machine just now, I get the following error:

```
warning NU1701: Package 'Coco 0.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net6.0'. This package may not be fully compatible with your project.
/var/folders/xg/drbz89cj6576cr7rz2h9n94c0000gn/T/vhdf4j35.3cx/restore.csproj : error NU1212: Invalid project-package combination for Coco 0.1.0. DotnetToolReference project style can only contain references of the DotnetTool type 
The tool package could not be restored.
```
