### ISSUE TITLE
Crash in ProverInterface when using AbstractHoudini

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#6]
Here is a small example causing this crash:

```
function {:existential true} b0(x:bool): bool;

var g: [int]int;
var g1: [int]int;

procedure main()
ensures b0(g == g1);
{}
```

Invoked command:

```
boogie.exe /doModSetAnalysis test.bpl /contractInfer /printAssignment /abstractHoudini:PredicateAbs /noinfer /inlineDepth:1
```

Akash helped in figuring out what is happening here. AbsHoudini tries to evaluate the value of the predicate; so it sends the following to the theorem prover:

```
(get-value ((= g g1)))
```

Z3 returns:

```
{(() (() (= g g1) true))}
```

Saying that the value is true. But the following method in ProverInterface isn't able to parse this string and crashes:

```
public override object Evaluate(VCExpr expr)
```

The fix would be to correct the parsing routine, but we don't understand this well enough. And we don't know why Z3 didn't just say "(true)" in the first place.

**Comment by delcypher** [comment]
I also see the crash. However the output of Z3 is a little different for me. If I capture the log using ``-proveLog:x.smt2`` I see (truncated)...

```
(set-option :print-success false)
(set-info :smt-lib-version 2.0)
(set-option :produce-models true)
(set-option :AUTO_CONFIG false)
(set-option :pp.bv_literals false)
(set-option :MODEL.V2 true)
(set-option :smt.PHASE_SELECTION 0)
(set-option :smt.RESTART_STRATEGY 0)
(set-option :smt.RESTART_FACTOR |1.5|)
(set-option :smt.ARITH.RANDOM_INITIAL_VALUE true)
(set-option :smt.CASE_SPLIT 3)
(set-option :smt.DELAY_UNITS true)
(set-option :NNF.SK_HACK true)
(set-option :smt.MBQI false)
(set-option :smt.QI.EAGER_THRESHOLD 100)
(set-option :smt.QI.COST |(+ weight generation)|)
(set-option :TYPE_CHECK true)
(set-option :smt.BV.REFLECT true)
; done setting options


(declare-fun tickleBool (Bool) Bool)
(assert (and (tickleBool true) (tickleBool false)))
(declare-fun %lbl%+40 () Bool)
(declare-fun %lbl%@82 () Bool)
(declare-fun AbsHoudiniConstant0 () Bool)
(declare-fun %lbl%+63 () Bool)
(define-fun mainMacro () Bool (let ((anon0_correct  (=> (! (and %lbl%+40 true) :lblpos +40) (! (or %lbl%@82  (=> true AbsHoudiniConstant0)) :lblneg @82))))
(let ((PreconditionGeneratedEntry_correct  (=> (! (and %lbl%+63 true) :lblpos +63) anon0_correct)))
PreconditionGeneratedEntry_correct)))
(declare-fun b0 (Bool) Bool)
(declare-fun g () (Array Int Int))
(declare-fun g1 () (Array Int Int))
(assert  (or true (b0 (= g g1))))
(push 1)
(assert  (not (=> (and (=> AbsHoudiniConstant0 false) (=> false AbsHoudiniConstant0)) mainMacro)))
(check-sat)
(labels)
(get-model)
(get-value ((= g g1)))
```

And Z3 4.3.2 responds with (truncated)

```
sat
(labels +63 +40 @82)
"AbsHoudiniConstant0 -> false
%lbl%+40 -> true
%lbl%@82 -> false
%lbl%+63 -> true
tickleBool -> {
  true -> true
  false -> true
  else -> true
}"
(((= g g1) true))
```

The ``(get-value)`` response looks correct to me. It's what is in the [SMT-LIBv2.5 draft](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.5-draft.pdf)

**Comment by shazqadeer** [comment]
Could it be that Zvonimir and Dan are using different versions of Z3?

**Comment by zvonimir** [comment]
I created the issue by merging what Akash learned about it and what I learned about it.
I am using Z3 4.3.2 too. I repeated Dan's steps and I do get the exact same outputs as Dan, including of course the crash.
It could be that Akash is using a different version of Z3.

**Comment by shazqadeer** [comment]
With Leo's help, I have triaged the issue.  The problem happens when Boogie asks Z3 to evaluate the expression g == g1, where g and g1 are maps. Z3's expression evaluation is expected to not be complete in this situation.  So, the result returned by Z3 is a partially-evaluated expression such as (= (_ as-array k!0) (_ as-array k!1)) which is simply a result of substituting the model for g and g1 in the equality.  Boogie then throws an exception because it expected true or false.  

So the upshot is that if we want some sensible behavior, we have to implement it at the Boogie end.  First, we need a proposal on what we want.

**Comment by zvonimir** [comment]
It is hard for me to say since I don't know who all the users of this functionality are. Maybe returning true/false/unknown instead of just true/false would make sense, and then clients of this functionality would have to deal with "unknown" sometimes being returned.

**Comment by shazqadeer** [comment]
Closing this issue since AbsHoudini is not being maintained at the moment.

@akashlal : FYI.
