### ISSUE TITLE
Default timeLimit leads to zero timeout

### ISSUE THREAD

**Issue by 0xabu** [boogie-org/boogie#62]
I noticed that if you don't pass a `/timeLimit` flag, Boogie tells Z3:
```
(set-option :TIMEOUT 0)
```
Unfortunately, due to https://github.com/Z3Prover/z3/issues/1100, this is implemented as an immediate timeout on Linux, whereas presumably the intention is to have an infinite timeout. It may be safer not to emit that line when a timeout isn't desired.

**Comment by 0xabu** [comment]
It turns out this issue (actually https://github.com/Z3Prover/z3/issues/791 of which mine was a dup) was fixed in Z3 but the released 4.5.0 builds have this error. It's probably still safer/better not to emit a 0 timeout if we don't want any timeout to occur, so I'm tempted to leave this open.

**Comment by shazqadeer** [comment]
This issue is fixed.
