### ISSUE TITLE
timeLimit attribute on procedures appears to no longer work

### ISSUE THREAD

**Issue by Chris-Hawblitzel** [boogie-org/boogie#63]
Boogie allows a per-procedure timeLimit attribute:

```
procedure{:timeLimit 10} p1() {}
procedure{:timeLimit 20} p2() {}
```

This used to produce a different TIMEOUT option on each of the two SMT queries:
```
(set-option :print-success false)
(set-info :smt-lib-version 2.0)
...
(set-option :TIMEOUT 10000)
...
(check-sat)
...
(set-option :TIMEOUT 20000)
(reset)
(set-option :TIMEOUT 20000)
(set-option :print-success false)
(set-info :smt-lib-version 2.0)
...
(set-option :TIMEOUT 20000)
...
(check-sat)
...
```

I think this may have unintentionally been changed in commit 09a9f17b9a8642f779ea0e5097c0aab8ce9f370b.  After that commit, the TIMEOUT is 10000 in both queries.

I'm not sure what the best fix is; as the commit rightly points out, the old code was messy (e.g. TIMEOUT 20000 is printed three times in the SMT code shown above) and the timeLimit attribute handling was Z3-specific.  But it would be nice if there were a way to make the timeLimit attribute work again.

**Comment by shazqadeer** [comment]
@bkragl : This issue suggests that Boogie used to support a time limit per implementation.  But now Boogie does not appear to do so.  For example, I tried to run Boogie on the program mentioned above:

procedure{:timeLimit 10} p1() {}
procedure{:timeLimit 20} p2() {}

When I look at the prover log file, I don't see any lines that set the timeout option.  So, it looks like the "timeLimit" attribute is being ignored.  I am wondering if this option got nuked when you did your cleanup.

**Comment by bkragl** [comment]
> I am wondering if this option got nuked when you did your cleanup.

No, this issue is much older. @Chris-Hawblitzel already pointed out commit 09a9f17b9a8642f779ea0e5097c0aab8ce9f370b, which changed this behavior. After having a brief look, I must agree that the code for setting timeouts is quite unwieldy.
