### ISSUE TITLE
CVC5 support?

### ISSUE THREAD

**Issue by hmijail** [boogie-org/boogie#737]
I'm looking into using Boogie with CVC5 (for Dafny). I see that the support is marked as "experimental" in the README, but what does that exactly mean? Is it expected to generally work? 

To get some impression of whether it works, I looked into Boogie's tests. I see that the driver tests' README states 
> We currently require Z3 4.

I tried anyway to run the tests with
> lit -v . --param boogie_params='/proverOpt:SOLVER=CVC5 /proverOpt:PROVER_PATH=/mypath/cvc5-macOS'  

(Boogie 2.16.7, CVC5 1.0.5, macOS 13.4 on ARM)

And a few tests pass, but it soon fails:
```
...
FAIL: Boogie :: bitvectors/arrays.bpl (9 of 584)
******************** TEST 'Boogie :: bitvectors/arrays.bpl' FAILED ********************
Script:
--
: 'RUN: at line 1';   dotnet /Users/mija/programming/boogie/Source/BoogieDriver/bin/Debug/net6.0/BoogieDriver.dll -useBaseNameForFileName /proverOpt:SOLVER=CVC5 /proverOpt:PROVER_PATH=/Users/mija/Downloads/cvc5-macOS /vcsCores:2 -proverWarnings:1 "/Users/mija/programming/boogie/Test/bitvectors/arrays.bpl" > "/Users/mija/programming/boogie/Test/bitvectors/Output/arrays.bpl.tmp"
: 'RUN: at line 2';   /usr/bin/diff --unified=3 --strip-trailing-cr --ignore-all-space "/Users/mija/programming/boogie/Test/bitvectors/arrays.bpl.expect" "/Users/mija/programming/boogie/Test/bitvectors/Output/arrays.bpl.tmp"
--
Exit Code: 1

Command Output (stdout):
--
$ ":" "RUN: at line 1"
$ "dotnet" "/Users/mija/programming/boogie/Source/BoogieDriver/bin/Debug/net6.0/BoogieDriver.dll" "-useBaseNameForFileName" "/proverOpt:SOLVER=CVC5" "/proverOpt:PROVER_PATH=/Users/mija/Downloads/cvc5-macOS" "/vcsCores:2" "-proverWarnings:1" "/Users/mija/programming/boogie/Test/bitvectors/arrays.bpl"
$ ":" "RUN: at line 2"
$ "/usr/bin/diff" "--unified=3" "--strip-trailing-cr" "--ignore-all-space" "/Users/mija/programming/boogie/Test/bitvectors/arrays.bpl.expect" "/Users/mija/programming/boogie/Test/bitvectors/Output/arrays.bpl.tmp"
# command output:
--- /Users/mija/programming/boogie/Test/bitvectors/arrays.bpl.expect	2023-05-29 13:36:02
+++ /Users/mija/programming/boogie/Test/bitvectors/Output/arrays.bpl.tmp	2023-05-29 13:40:27
@@ -1,2 +1,6 @@
+Advisory: bar SKIPPED due to I/O exception: Pipe is broken.
+Advisory: foo SKIPPED due to I/O exception: Pipe is broken.
+arrays.bpl(12,11): Verification encountered solver exception (foo)
+arrays.bpl(32,11): Verification encountered solver exception (bar)

-Boogie program verifier finished with 2 verified, 0 errors
+Boogie program verifier finished with 0 verified, 0 errors, 2 solver exceptions

error: command failed with exit status: 1

--
...
```

After that, some pass, some fail.

So, can you clarify what is the level of support for CVC5? Should the tests pass? Should a particular release of CVC5 be used?

**Comment by shazqadeer** [comment]
Boogie regression test suite has never been systematically evaluated for compatibility with CVC5. 

I looked deeper into the problem with arrays.bpl. It looks like CVC5 is unable to parse the following array sort:
```
(Array T@ref T@Field_14 Int)
```
The above is a 2-D array which apparently Z3 supports. It looks like CVC5 only supports 1-D arrays.

I tried CVC5 on a few other tests in the bitvector folder and they seem to work.

The benchmarks in civl folder use the generalized array theory, something that is supported by Z3 but not CVC5.

Overall, it looks to me that Boogie generates SMT2 output that is more than what is expected in SMTLIB standard. These extensions work with Z3 but CVC5 does not support them.

I would think that as long as the Boogie program stays within the subset expected by CVC5, things should work.

**Comment by DavePearce** [comment]
Hey @shazqadeer,

So, are there any work arounds here?  For example, is it possible Dafny could generate Boogie code to simulate a 2D array using only 1D arrays?   Or does it really come down to something that would need to be added to CVC5?

**Comment by shazqadeer** [comment]
I think it is possible to simulate n-dim array by nested 1-dim arrays. Please consult @RustanLeino .
