### ISSUE TITLE
Debugging support in Boogie

### ISSUE THREAD

**Issue by sreeja** [boogie-org/boogie#74]
I am working on a project using Boogie for verifying distributed applications. In my work I am in need of a better debugging support when a verification fails.

I browsed through the command line options and have found the following options useful in my context:
1. `\mv`
2. `\z3multipleErrors`
3. `\break`
I tried them and have some issues/questions.

I will try to explain my issue through a trivial example. Below is a Boogie specification for incrementing a counter.

counter.bpl :::
```
var counter: int;
procedure increment(value: int)
modifies counter;
ensures (counter >= 0);
{
  assume(counter >= 0);
  counter := counter + value;
}
```

I am executing the command line as follows : `Boogie.exe /z3multipleErrors /mv:counter.model counter.bpl`

The result is :
```
Boogie program verifier version 2.3.0.61016, Copyright (c) 2003-2014, Microsoft.
counter.bpl(10,1): Error BP5003: A postcondition might not hold on this return path.
counter.bpl(5,1): Related location: This is the postcondition that might not hold.
Execution trace:
    counter.bpl(7,3): anon0

Boogie program verifier finished with 0 verified, 1 error
```
and the model is :

counter.model:::
```
*** MODEL
%lbl%@82 -> false
%lbl%+37 -> true
%lbl%+45 -> true
counter -> 0
counter@0 -> (- 1)
value -> (- 1)
tickleBool -> {
  true -> true
  false -> true
  else -> true
}
*** END_MODEL
```
The counter example in this case is when the `value` to be incremented is -1 when `counter` is 0. But I would like to have more counter examples. So I have two questions here :
1. I expected the `/z3multipleErrors` option to give me multiple counter examples, in this particular case something like `[counter = 0 & value = -1, -2, -3,..], [counter = 1 & value = -2, -3, ...]` etc. Then I plan to use the set of values to get insights into the error, in this case `value` is negative. Am I missing something here?
2. Is the counter example the "minimal counter example"? I know this case is a trivial example, but I wish to know if I always get a minimal counter example.
Suppose I have a linked list which I am checking whether it is linear. As a counter example, I can have the following results:
`1 -> 1` or `1 -> 2 -> 3 -> 4 ..... -> 1`
Both are ideally counter examples, but the first one is a minimal counter example.

Now coming to the next stage of my issue. 
The counter example is pretty comprehensible when the data types involved are simple. When I use maps or nested maps like below, the counter examples generated run into several pages and it is tiresome to try to understand it. I am giving a trivial example of a 2D matrix which has a constraint that all its elements should be non-negative.

matrix.bpl:::
```
var matrix: [int][int]int;
procedure modify(row:int, column:int, value: int)
modifies matrix;
ensures (forall r, c:int :: matrix[r][c] >= 0);
{
  assume(forall r, c:int :: matrix[r][c] >= 0);
  matrix[row][column] := matrix[row][column] + value;
}
```
matrix.model:::
```
*** MODEL
%lbl%@193 -> false
%lbl%+104 -> true
%lbl%+79 -> true
c@@0!0!0 -> 2
column -> 2
matrix -> |T@[Int][Int]Int!val!0|
matrix@0 -> |T@[Int][Int]Int!val!1|
r@@0!0!1 -> 1
row -> 1
value -> (- 563)
Store_[$int]$int -> {
  |T@[Int]Int!val!1| 2 (- 563) -> |T@[Int]Int!val!0|
  else -> |T@[Int]Int!val!0|
}
Select_[$int]$int -> {
  |T@[Int]Int!val!0| 2 -> (- 563)
  |T@[Int]Int!val!1| 2 -> 0
  else -> (- 563)
}
tickleBool -> {
  true -> true
  false -> true
  else -> true
}
Select_[$int][$int]$int -> {
  |T@[Int][Int]Int!val!1| 1 -> |T@[Int]Int!val!0|
  |T@[Int][Int]Int!val!0| 1 -> |T@[Int]Int!val!1|
  else -> |T@[Int]Int!val!0|
}
Store_[$int][$int]$int -> {
  |T@[Int][Int]Int!val!0| 1 |T@[Int]Int!val!0| -> |T@[Int][Int]Int!val!1|
  else -> |T@[Int][Int]Int!val!1|
}
*** END_MODEL
```
Ideally the inference here should be the same as the non-negative counter above, ie, the value should be non-negative. But understanding that information from this counter example requires a lot of effort.

I have two questions in this context:
1. Is there any on going effort in making the counter example comprehensible for non-expert users? I have seen the BVD interface, but I felt it a small beautification of the plain text model.
2. The description of the `\break` flag looks promising, but I see it is not yet implemented. It would be useful to know the status of that. Is there some work in progress?

Thank you for taking your time out to read this lengthy report. I would appreciate any help, even if it only addresses a small part of the question.

--
Sreeja.

PS: I had tried to send this to the mailing list. I got a notice indicating the decision is with the moderator and it was a week back.

**Comment by bkragl** [comment]
Sorry for the (very) late response!

> I expected the `/z3multipleErrors` option to give me multiple counter examples, in this particular case something like `[counter = 0 & value = -1, -2, -3,..], [counter = 1 & value = -2, -3, ...]` etc. Then I plan to use the set of values to get insights into the error, in this case `value` is negative. Am I missing something here?

The `/z3multipleErrors` option does not exist anymore, but I don't think it could have given you the kind of sophisticated error explanation you are looking for out of the box.

> Is the counter example the "minimal counter example"?

No. Boogie processes whichever model the underlying theorem prover could produce.

> Is there any on going effort in making the counter example comprehensible for non-expert users? I have seen the BVD interface, but I felt it a small beautification of the plain text model.

I'm not aware of any such effort.

> The description of the `\break` flag looks promising, but I see it is not yet implemented. It would be useful to know the status of that. Is there some work in progress?

This is actually a legacy flag that should be removed. It has to do with attaching a debugger to the Boogie process (i.e., debugging Boogie itself, not debugging a Boogie program).
