### ISSUE TITLE
Pruning removes too much

### ISSUE THREAD

**Issue by atomb** [boogie-org/boogie#747]
Consider the following Boogie program.

```
type Seq;

function Seq#Length(Seq) : int;

function Seq#Empty() : Seq;

function Seq#Build(s: Seq, val: int) : Seq;

axiom Seq#Length(Seq#Empty()) == 0;

axiom (forall s: Seq, v: int ::
  { Seq#Build(s, v) } 
  Seq#Length(Seq#Build(s, v)) == 1 + Seq#Length(s));

procedure P()
{
  var s#0: Seq;
  s#0 := Seq#Build(Seq#Empty(), 1);
  assert 0 <= Seq#Length(s#0);
}
```

This has different behavior with `/prune` vs. without.

```
$ boogie array-minimized.bpl

Boogie program verifier finished with 1 verified, 0 errors
$ boogie /prune array-minimized.bpl
array-minimized.bpl(19,3): Error: this assertion could not be proved
Execution trace:
    array-minimized.bpl(18,7): anon0

Boogie program verifier finished with 0 verified, 1 error
```

**Comment by atomb** [comment]
It looks as though Boogie is pruning `axiom Seq#Length(Seq#Empty()) == 0;`.

**Comment by shazqadeer** [comment]
Could it be that you have to use the `uses` clause? See this [sample](https://github.com/boogie-org/boogie/blob/master/Test/pruning/UsesClauses.bpl).

**Comment by keyboardDrummer** [comment]
The best documentation for pruning is the comment on the `CommandLineOptions.Prune` field. It might be better if we move that to the CLI help. Would that have helped you?

**Comment by atomb** [comment]
Putting that axiom in the `uses` clause of `Seq#Length` or `Seq#Empty` does fix the problem, but it's still a bit surprising to me that it gets pruned otherwise.

**Comment by atomb** [comment]
I can confirm that a `uses` clause fixes the larger example where this occurred, so I'm closing the issue.
