### ISSUE TITLE
Is there any up-to-date language reference?

### ISSUE THREAD

**Issue by glor** [boogie-org/boogie#779]
It looked at the docs and found and can't find anything except the Language reference (which seems to contain more TODOs than content) and a paper from 2008 ("This is Boogie 2"). Since there are multiple frontends for Boogie IVL I wondered if there is any Getting started guide or any more complete or up to date reference for the language?

**Comment by shazqadeer** [comment]
What kind of documentation are you looking for? A precise language reference with a BNF, or informal conceptual explanation using examples, or something else.

I wrote a tutorial for the Civl subset of Boogie [here](https://civl-verifier.github.io/doc). This tutorial explains concepts using examples and is not a precise language reference. Would something like this tutorial but covering all the basic Boogie features as well satisfy you?

**Comment by shazqadeer** [comment]
Closing this issue for now. Please reopen if necessary.
