### ISSUE TITLE
/errorLimit parameter quirks (default and 0-parameter behaviours)

### ISSUE THREAD

**Issue by alexanderjsummers** [boogie-org/boogie#79]
By default, Boogie limits the number of errors reported per procedure. Since this isn't documented except in the /help, I found it a bit surprising when first flagged.

It seems that the /errorLimit:n parameter is, by default, set to 5. If one sets this to a higher number, more errors are reported. However, there doesn't seem to be a way (in principle) to avoid limiting the number of errors seen (of course, one can just choose a very large number each time). Passing /errorLimit:0 behaves analogously to /errorLimit:1 - one sees neither all nor zero errors.

I suggest that the default behaviour should be _not_ to include a hard limit on the number of errors produced per procedure. One could discuss how a 0 parameter should be treated - personally I would find the "no limit" interpretation more useful there, too. In any case, the 0 shouldn't be treated as a 1.

**Comment by RustanLeino** [comment]
I agree that it would be good to support a no-limit mode. Regardless of what the default limit is, it is useful to be able to specify any option (including no-limit) from the command line. Furthermore, whatever the default is should be reported with the `/help` switch.

  Rustan

**Comment by shazqadeer** [comment]
@alexanderjsummers : Do you still care about this issue?  If yes, please suggest a strategy for implementing unlimited number of detected errors.  If not, I will simply change Boogie to print out an error message for /errorLimit:0 and close this issue.

**Comment by alexanderjsummers** [comment]
Hi Shaz,

Yes - we use Boogie assuming that it will report all errors. I assume other users of Boogie as a back-end might do the same (but perhaps not realise that some errors are omitted). By strategy, do you mean where in the code the limit should be removed? Or is there a deeper issue that I'm not aware of?

What is the motivation for having a limit at all (by default)?

Thanks, Alex

**Comment by shazqadeer** [comment]
What does it mean to report all errors?

**Comment by alexanderjsummers** [comment]
Hi Shaz. I'm not sure if understand your question. 

I believe that Boogie currently treats each statement generating a verification requirement as an assert-assume pair; in this way, the remainder of the program is still analysed under the assumption that all previous verification conditions were successful. This is how I learned when I should expect Boogie to e.g. produce 2 rather than 1 error, and when I should not (e.g. because a later statement's VC is entirely subsumed by the previous assumptions). By the same logic, I understand when I expect an (n+1)th error from a particular line, and can incrementally walk through the program and figure out which lines should report a further error (or not).

One can alternatively explain this using the trace semantics defined in the "This is Boogie 2" paper; one should get an error for every statement reachable by some trace for which the statement's requirement (I guess this is only asserts once everything is desugared) does not hold. This gives the set of failing statements. The semantics outlined there includes cutting recursion/loops, I believe, so this is always finitely many.

All errors would mean that Boogie reports all of these failing statements. Does that make sense?

Thanks, Alex

**Comment by shazqadeer** [comment]
So, if an assertion can fail along two different paths, you want at least one but not necessarily both?

**Comment by alexanderjsummers** [comment]
Hi Shaz,

That would be ideal for our purposes, yes. I think that's how Boogie works at present (even with the limit), isn't it? I don't think we get multiple errors for the same source location even if those errors hadn't yet hit the threshold enforced by errorLimit (but that's OK for us).

I guess a different way of looking at it is that we would like the behaviour of the current /errorLimit:n if you let n tend to infinity :)

Cheers, Alex

**Comment by alexanderjsummers** [comment]
Just a side-remark: of course, there can be (infinitely) many ways for a single line to be reached with a failure even without different paths (just varying the values in the counter-examples). But again, we're happy with just one per location (just as Boogie currently does it).

**Comment by shazqadeer** [comment]
I understand what you want.  I will report back.

**Comment by shazqadeer** [comment]
PR #262 addresses this issue.
