### ISSUE TITLE
Sanitize the . (DOT) prefix for CVC4 support

### ISSUE THREAD

**Issue by pdeligia** [boogie-org/boogie#8]
Hi guys,

So SMACK can produce some constants that start with the . (DOT) prefix (e.g. const unique .str: int;). This can cause issues when Boogie sends the SMTLIBv2 formula to CVC4, because the @ and . prefixes are reserved in the standard (see * below).

I think (I might be wrong though) that there already exists some pass inside Boogie that changes the prefix @ to "AT". Could we do the same for the dot prefix?

Any thoughts?

Cheers,

Pantazis

---

*[quote from the SMTLIBv2 standard]: Symbols are used for attribute values, and sort, variable, logic, theory, constant and function names. A symbol can be any sequence of symbol characters that does not start with a digit and is not a reserved word. In addition, user-defined symbols may not begin with an @ or a period (.); such symbols are reserved for internal use. Some symbols consisting of punctuation characters, such as + and - have intuitively natural meanings as function symbols, though their meaning is always defined solely by the logic being used. Similarly, symbols that are English words may have obvious meanings. Good style would suggest avoiding legal but unusual symbols that mix alphanumerics and operator-like characters, such as a<b or ab+- or -1.

**Comment by delcypher** [comment]
There's already an open issue (#7) for this.

**Comment by pdeligia** [comment]
I just saw that! :-( Can you delete please?

**Comment by delcypher** [comment]
@pdeligia It can't be deleted, it can only closed (which it already is).

**Comment by pdeligia** [comment]
@delcypher Oh, I did not know that, thanks though.
