### ISSUE TITLE
Switching Boogie build to .NET Standard/Core

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/boogie#81]
Recently I started looking into how to improve the portability of Boogie across platforms, and in particular whether it can be compiled using Microsoft's dotnet core distribution for Linux. After reading a bit about various .NET implementations, it seems to me that it would be good to switch Boogie from .NET Framework v4.5 (which it currently requires) to something that is more portable, such as .NET standard/core. (Note that .NET Framework is not available on Linux from Microsoft, while .NET Core is - see https://www.microsoft.com/net/download/linux)

Based on my understanding, switching to .NET Standard/Core ought to be possible (and hopefully not too hard) since Boogie is a command line application that does not use GUI.

Note that I was quite confused about what the heck .NET Framework, Core, and Standard are, and this is a good place to start learning about this: https://msdn.microsoft.com/en-us/magazine/mt842506.aspx

Anyhow, I would like to start a discussion regarding this switch, and maybe get opinions and/or suggestions from people who understand the potential issues and how to go about this better.

**Comment by RustanLeino** [comment]
Boogie is also used by Dafny, including from within the Dafny plug-in for Visual Studio. Will that still work with .NET Core?

**Comment by zvonimir** [comment]
I suspect that in this scenario Boogie is being invoked as a library. My understanding is that should still work. In fact, .NET Core is mentioned as the best option for implementing libraries if one is interested in portability. If there are GUI aspects within Boogie, then that would probably create problems.
Having said that, I am certainly not an expert on these .NET portability issues/frameworks, and it would be good to get some input from someone who has a better understanding of this landscape and options. Which is why I created this issue.

**Comment by shazqadeer** [comment]
I believe this issue has been addressed by the work done by @michael-emmi and @bkragl.  Boogie now builds with .NET Core and Standard.  The travis build is .NET core.  So closing the issue now.  Please reopen if necessary explaining what remains unaddressed.
