### ISSUE TITLE
Verification fails in the presence of a dummy/unused function

### ISSUE THREAD

**Issue by zhassan-aws** [boogie-org/boogie#824]
For the following Boogie program:
```
var heap: [int]int;

procedure zero(offset: int, len: int)
  requires len >= 0;
  requires offset >= 0;
  modifies heap;
{
  var index: int;
  index := 0;
  while (index < len)
    invariant (forall i: int:: (0 <= i && i < index ==> (heap[offset + i] == 0)));
    invariant index <= len;
  {
    heap[offset + index] := 0;
    index := index + 1;
  }
}

//function dummy(x: int) returns (bool) {
//  x > 5
//}
```
Verification passes:
```
$ boogie bug.bpl

Boogie program verifier finished with 1 verified, 0 errors
```
but if I uncomment the dummy function, verification fails:
```
$ boogie bug.bpl
bug.bpl(11,5): Error: this invariant could not be proved to be maintained by the loop
Execution trace:
    bug.bpl(9,9): anon0
    bug.bpl(10,3): anon2_LoopHead
    bug.bpl(14,26): anon2_LoopBody

Boogie program verifier finished with 0 verified, 1 error
```
Is this expected? If I run with `/prune`, verification passes.

Boogie version:
```
$ boogie /version
Boogie program verifier version 3.0.8.0, Copyright (c) 2003-2014, Microsoft.
```

**Comment by shazqadeer** [comment]
You are seeing the flakiness that is typical when quantifier instantiation on specific terms is needed for proving the verification condition. In these cases, small unrelated differences in the execution environment can cause verification to succeed or fail.

Boogie has features for the user to provide hints for quantifier instantiation which could be mechanism for trading off proof robustness for automation. If you are interested in these mechanisms, I can provide pointers.

**Comment by shazqadeer** [comment]
Quantifier triggers is definitely a relevant mechanism. It sounds like you are already aware of them so I won't provide any more pointers. 

Another mechanism, added recently, is pool-based quantifier instantiation which offers more control compared to triggers. There is a tutorial [here](https://civl-verifier.github.io/doc#quantifier-instantiation-pools) and more samples [here](https://github.com/boogie-org/boogie/tree/master/Test/inst).

I am happy to answer any questions about triggers or instantiation pools.

**Comment by zhassan-aws** [comment]
Thanks!
