### ISSUE TITLE
Possibly Missing Interpolation in SMTLibInteractiveTheoremProver

### ISSUE THREAD

**Issue by Marti2203** [boogie-org/boogie#863]
Hi,
I was reading the source code of the SMTLibInteractiveTheoremProver class, and I saw that line 812 has the following context:
```csharp
foreach (var relaxVar in relaxVars)
{
  var resp = await SendVcRequest("(get-value ({relaxVar}))").WaitAsync(cancellationToken);
...
```
I saw this as highly suspicious, prompting me to open this issue. Should there not be a $ before `"(get-value...`?

**Comment by atomb** [comment]
> I saw this as highly suspicious, prompting me to open this issue. Should there not be a $ before `"(get-value...`

Oh, I think you're right! Fortunately that's easy to fix. It makes me think that no one has been using this functionality for a while.

**Comment by Marti2203** [comment]
Hi, happy to hear that it is not a false positive :) I saw that only Houdini uses it but it is still good to keep things correct.
