### ISSUE TITLE
Are VcOutcome.ReachedBound and CommandLineOptions.RecursionBound obsolete?

### ISSUE THREAD

**Issue by shazqadeer** [boogie-org/boogie#936]
@akashlal : While looking into one the recently posted issue #921, I discovered that we still have some Corral related fields in Boogie, notably the two fields mentioned in the title of this issue. They don't appear to be used in Boogie to the best of my understanding.  Could you please confirm? Does Corral need them to stay in Boogie?

**Comment by akashlal** [comment]
Corral isn't actively used any more, to the best of my knowledge. It is anyway best to remove these flags from Boogie if they're not getting used. When, and if, corral upgrades its boogie version then it will have to find a workaround.
