### ISSUE TITLE
Modelling a fixed length vector / array in Boogie.

### ISSUE THREAD

**Issue by tyrbentsen** [boogie-org/boogie#98]
I'm trying to model fixed length vectors in Boogie. Each vector with a different size should be a different type.

I tried two approaches, but both have a particular problem.

## Approach 1: Type aliases

Define a type alias and some axioms that describe the length for the type alias. However, since only an alias is created and not a new type, the axioms are valid for all aliases. Hence, we get conflicting axioms.

    function length(x: [int]real) returns (n: int);
    
    type Vector3 = [int]real;
    axiom (forall x: Vector3 :: length(x) == 3);
    
    type Vector5 = [int]real;
    // The following axiom conflicts with the previous one.
    axiom (forall x: Vector5 :: length(x) == 5); 
    			
    procedure impl1();
    implementation impl1()
    {
      var v1: Vector3;
      var v2: Vector5;
    
        v1[0] := 1.0;
    	v1[0] := 2.0;
    	v1[0] := 3.0;
    	
    	assert length(v1) == 3;
    	assert length(v2) == 5;
    	assert length(v1) == 999; // Must fail but it doesn't.
    }

## Approach 2: Fresh types

Here we create a fresh type for each fixed length vector, with a marker 'Dim3' to make it unique. The length is described using an axiom. The problem here is that I don't know how to access/assign to the map that is part of this type.

    function length<D>(x: Vector D [int]real) returns (n: int);
    
    type Vector alpha beta;
    
    type Dim1;
    type Dim2;
    type Dim3;
    type Dim4;
    type Dim5;
    
    type Vector3 = Vector Dim3 [int]real;
    axiom (forall x: Vector3 :: length(x) == 3);
    
    type Vector5 = Vector Dim5 [int]real;
    axiom (forall x: Vector5 :: length(x) == 5);
    
    
    procedure impl1();
    implementation impl1()
    {
      var v1: Vector3;
      var v2: Vector5;
    
        v1[0] := 1.0; // Invalid boogie code: 'Error: map assignment applied to a non-map'
    	v1[0] := 2.0;
    	v1[0] := 3.0;
    	
    	assert length(v1) == 3;
    	assert length(v2) == 5;	
    }

I would be glad if someone can point me in the right direction!

**Comment by shazqadeer** [comment]
It is indeed annoying that Boogie does not provide fixed-length or, in general, finite-length arrays.  I can offer suggestions but I need to understand a bit more.  Do you need to be able to reason about equality over your fixed-length arrays?  Or do you just need to look up and update values in them?

**Comment by RustanLeino** [comment]
To use a fixed-length array, you'd want to enforce a check on the index. It is not in the style of Boogie to impose such proof obligations on the use of expressions. More in the Boogie spirit would be to define a language of top of Boogie that gives rise to such proof obligations. The proof obligations would then be translated into `assert` statements in Boogie.
